import { strict as assert } from 'node:assert';
import { test } from 'node:test';
import path from 'node:path';
import url from 'node:url';

import { PhpCliNode } from '../../packages/php-cli-wasm/PhpCliNode.mjs';
import { nodeRuntimeOptions } from '../lib/node-runtime-options.mjs';
import { runCliPhpt } from '../lib/phpt.mjs';

const version = process.env.PHP_VERSION ?? '8.4';
const here = path.dirname(url.fileURLToPath(import.meta.url));
const phpt = name => path.resolve(here, `../../third_party/php${version}-src/tests/lang/${name}.phpt`);
const extPhpt = (extension, name) => path.resolve(here, `../../third_party/php${version}-src/ext/${extension}/tests/${name}`);
const directCliPhpts = [
	'001',
	'002',
	'003',
	'004',
	'005',
	'006',
	'007',
	'008',
	'009',
	'010',
	'011',
	'012',
	'013',
	'014',
	'015',
	'016',
	'017',
	'018',
	'019',
	'020',
	'021',
	'022',
	'023',
	'026',
	'027',
	'028',
	'030',
	'032',
	'033',
	'035',
	'036',
	'037',
	'038',
	'039',
	'040',
	'041',
	'042',
	'043',
	'044',
	'array_shortcut_001',
	'array_shortcut_002',
	'array_shortcut_003',
	'array_shortcut_005',
	'bison1',
	'bug18872',
	'bug19566',
	'bug19943',
	'bug20175',
	'bug21094',
	'bug21600',
	'bug21669',
	'bug21820',
	'bug21849',
	'bug21961',
	'bug22231',
	'bug22510',
	'bug22592',
	'bug23279',
	'bug23384',
	'bug23489',
	'bug23524',
	'bug23584',
	'bug23624',
	'bug24054',
	'bug24396',
	'bug24436',
	'bug24499',
	'bug24573',
	'bug24640',
	'bug24652',
	'bug24658',
	'bug24783',
	'bug24908',
	'bug24951',
	'bug25547',
	'bug25652',
	'bug25922',
	'bug26182',
	'bug26696',
	'bug26866',
	'bug26869',
	'bug27354',
	'bug27439',
	'bug27443',
	'bug27535',
	'bug28213',
	'bug28800',
	'bug29566',
	'bug29893',
	'bug29944',
	'bug30578',
	'bug30726',
	'bug30862',
	'bug32828',
	'bug32924',
	'bug35176',
	'bug35382',
	'bug43958',
	'bug44654',
	'bug44827',
	'bug55754',
	'bug71897',
	'bug73172',
	'bug73329',
	'bug7515',
	'catchable_error_001',
	'catchable_error_002',
	'comments',
	'comments2',
	'compare_objects_basic1',
	'compare_objects_basic2',
	'empty_variation',
	'engine_assignExecutionOrder_001',
	'engine_assignExecutionOrder_002',
	'engine_assignExecutionOrder_003',
	'engine_assignExecutionOrder_004',
	'engine_assignExecutionOrder_005',
	'engine_assignExecutionOrder_006',
	'engine_assignExecutionOrder_007',
	'engine_assignExecutionOrder_008',
	'engine_assignExecutionOrder_009',
	'error_2_exception_001',
	'execution_order',
	'foreach_with_object_001',
	'foreach_with_references_001',
	'foreachLoop.001',
	'foreachLoop.002',
	'foreachLoop.003',
	'foreachLoop.004',
	'foreachLoop.005',
	'foreachLoop.006',
	'foreachLoop.009',
	'foreachLoop.010',
	'foreachLoop.011',
	'foreachLoop.012',
	'foreachLoop.013',
	'foreachLoop.014',
	'foreachLoop.015',
	'foreachLoop.016',
	'foreachLoop.017',
	'foreachLoopIterator.001',
	'foreachLoopIterator.002',
	'foreachLoopIteratorAggregate.001',
	'foreachLoopIteratorAggregate.002',
	'foreachLoopIteratorAggregate.003',
	'foreachLoopIteratorAggregate.004',
	'foreachLoopObjects.001',
	'foreachLoopObjects.002',
	'foreachLoopObjects.003',
	'foreachLoopObjects.004',
	'foreachLoopObjects.005',
	'foreachLoopObjects.006',
	'func_get_arg_variation',
	'func_get_arg.001',
	'func_get_arg.002',
	'func_get_arg.003',
	'func_get_arg.004',
	'func_get_arg.005',
	'func_get_args.001',
	'func_get_args.002',
	'func_get_args.003',
	'func_get_args.004',
	'func_num_args.001',
	'func_num_args.002',
	'func_num_args.003',
	'func_num_args.004',
	'include_variation1',
	'include_variation2',
	'include_variation3',
	'invalid_octal',
	'passByReference_001',
	'passByReference_002',
	'passByReference_003',
	'passByReference_004',
	'passByReference_005',
	'passByReference_006',
	'passByReference_007',
	'passByReference_008',
	'passByReference_009',
	'passByReference_010',
	'passByReference_012',
	'returnByReference.001',
	'returnByReference.002',
	'returnByReference.003',
	'returnByReference.004',
	'returnByReference.005',
	'returnByReference.006',
	'returnByReference.007',
	'returnByReference.008',
	'returnByReference.009',
	'short_tags.001',
	'short_tags.002',
	'short_tags.004',
	'static_basic_001',
	'static_basic_002',
	'static_variation_001',
	'static_variation_002',
	'string_decimals_001',
	'syntax_errors',
	'this_assignment',
	'throw_variation_001',
	'type_hints_001',
	'type_hints_002',
	'type_hints_003',
	'zend_throw_exception_001'
];
const directCliExtensionPhpts = [
	['simplexml', '000.phpt'],
	['simplexml', '001-mb.phpt'],
	['simplexml', '001.phpt'],
	['simplexml', '002.phpt'],
	['simplexml', '003.phpt'],
	['simplexml', '004.phpt'],
	['simplexml', '005.phpt'],
	['simplexml', '006.phpt'],
	['simplexml', '007.phpt'],
	['simplexml', '008.phpt'],
	['simplexml', '009.phpt'],
	['simplexml', '009b.phpt'],
	['simplexml', '010.phpt'],
	['simplexml', '011.phpt'],
	['simplexml', '012.phpt'],
	['simplexml', '013.phpt'],
	['simplexml', '014.phpt'],
	['simplexml', '014a.phpt'],
	['simplexml', '014b.phpt'],
	['simplexml', '015.phpt'],
	['simplexml', '016.phpt'],
	['simplexml', '016a.phpt'],
	['simplexml', '017.phpt'],
	['simplexml', '018.phpt'],
	['simplexml', '019.phpt'],
	['simplexml', '020.phpt'],
	['simplexml', '021.phpt'],
	['simplexml', '022.phpt'],
	['simplexml', '023.phpt'],
	['simplexml', '024.phpt'],
	['simplexml', '025.phpt'],
	['simplexml', '026.phpt'],
	['simplexml', '027.phpt'],
	['simplexml', '028.phpt'],
	['simplexml', '029.phpt'],
	['simplexml', '030.phpt'],
	['simplexml', '031.phpt'],
	['simplexml', '032.phpt'],
	['simplexml', '033.phpt'],
	['simplexml', '034.phpt'],
	['simplexml', '035.phpt'],
	['simplexml', '036.phpt'],
	['simplexml', '037.phpt'],
	['simplexml', '038.phpt'],
	['simplexml', 'bug12170.phpt'],
	['simplexml', 'bug24392.phpt'],
	['simplexml', 'bug26976.phpt'],
	['simplexml', 'bug27010.phpt'],
	['simplexml', 'bug35785.phpt'],
	['simplexml', 'bug36611.phpt'],
	['simplexml', 'bug37076_1.phpt'],
	['simplexml', 'bug37076.phpt'],
	['simplexml', 'bug37386.phpt'],
	['simplexml', 'bug38347.phpt'],
	['simplexml', 'bug38354.phpt'],
	['simplexml', 'bug38406.phpt'],
	['simplexml', 'bug38424.phpt'],
	['simplexml', 'bug39662.phpt'],
	['simplexml', 'bug39760.phpt'],
	['simplexml', 'bug40451.phpt'],
	['simplexml', 'bug41175.phpt'],
	['simplexml', 'bug41582.phpt'],
	['simplexml', 'bug41861.phpt'],
	['simplexml', 'bug41867.phpt'],
	['simplexml', 'bug41947.phpt'],
	['simplexml', 'bug42259.phpt'],
	['simplexml', 'bug42369.phpt'],
	['simplexml', 'bug43221.phpt'],
	['simplexml', 'bug44478.phpt'],
	['simplexml', 'bug45553.phpt'],
	['simplexml', 'bug46003.phpt'],
	['simplexml', 'bug46047.phpt'],
	['simplexml', 'bug46048.phpt'],
	['simplexml', 'bug48601.phpt'],
	['simplexml', 'bug51615.phpt'],
	['simplexml', 'bug52751.phpt'],
	['simplexml', 'bug53033.phpt'],
	['simplexml', 'bug54973.phpt'],
	['simplexml', 'bug61335.phpt'],
	['simplexml', 'bug62328.phpt'],
	['simplexml', 'bug62639.phpt'],
	['simplexml', 'bug63575.phpt'],
	['simplexml', 'bug66084_0.phpt'],
	['simplexml', 'bug66084_1.phpt'],
	['simplexml', 'bug67116.phpt'],
	['simplexml', 'bug67572.phpt'],
	['simplexml', 'bug69169.phpt'],
	['simplexml', 'bug69491.phpt'],
	['simplexml', 'bug72588.phpt'],
	['simplexml', 'bug72957.phpt'],
	['simplexml', 'bug72971_2.phpt'],
	['simplexml', 'bug72971.phpt'],
	['simplexml', 'bug75245.phpt'],
	['simplexml', 'bug76712.phpt'],
	['simplexml', 'bug81325.phpt'],
	['simplexml', 'current_error.phpt'],
	['simplexml', 'feature55218.phpt'],
	['simplexml', 'foreach_by_reference.phpt'],
	['simplexml', 'get_prop_address_not_initialized.phpt'],
	['simplexml', 'gh10200.phpt'],
	['simplexml', 'gh10983.phpt'],
	['simplexml', 'gh12167.phpt'],
	['simplexml', 'gh12169.phpt'],
	['simplexml', 'gh12223.phpt'],
	['simplexml', 'gh12929.phpt'],
	['simplexml', 'gh14638.phpt'],
	['simplexml', 'key_error.phpt'],
	['simplexml', 'profile11.phpt'],
	['simplexml', 'profile12.phpt'],
	['simplexml', 'profile13.phpt'],
	['simplexml', 'profile01.phpt'],
	['simplexml', 'profile02.phpt'],
	['simplexml', 'profile03.phpt'],
	['simplexml', 'profile04.phpt'],
	['simplexml', 'profile05.phpt'],
	['simplexml', 'profile06.phpt'],
	['simplexml', 'profile07.phpt'],
	['simplexml', 'profile08.phpt'],
	['simplexml', 'profile09.phpt'],
	['simplexml', 'profile10.phpt'],
	['simplexml', 'simplexml_import_dom.phpt'],
	['simplexml', 'simplexml_load_file.phpt'],
	['simplexml', 'simplexml_uninitialized.phpt'],
	['simplexml', 'SimpleXMLElement_addAttribute_basic.phpt'],
	['simplexml', 'SimpleXMLElement_addAttribute_required_attribute_name.phpt'],
	['simplexml', 'SimpleXMLElement_getDocNamespaces.phpt'],
	['simplexml', 'SimpleXMLElement_xpath.phpt'],
	['simplexml', 'sxe_001.phpt'],
	['simplexml', 'sxe_002.phpt'],
	['simplexml', 'sxe_003.phpt'],
	['simplexml', 'sxe_004.phpt'],
	['simplexml', 'sxe_005.phpt'],
	['dom', 'DOMDocument_loadHTMLfile_variation1.phpt'],
	['zlib', '001.phpt'],
	['zlib', '002.phpt'],
	['zlib', '005.phpt'],
	['sqlite3', 'sqlite3_01_open.phpt'],
	['sqlite3', 'bug45798.phpt'],
	['sqlite3', 'bug53463.phpt'],
	['tidy', '001.phpt'],
	['tidy', '006.phpt'],
	['iconv', 'bug48147.phpt'],
	['iconv', 'bug51250.phpt'],
	['iconv', 'bug53304.phpt'],
	['intl', 'badargs.phpt'],
	['intl', 'intl_icu_data_version_constant.phpt'],
	['xmlwriter', '001.phpt'],
	['xmlwriter', '002.phpt'],
	['xmlwriter', '003.phpt'],
	['xmlwriter', '004.phpt'],
	['xmlwriter', '005-mb.phpt'],
	['xmlwriter', '005.phpt'],
	['xmlwriter', '006.phpt'],
	['xmlwriter', '007.phpt'],
	['xmlwriter', '008.phpt'],
	['xmlwriter', '009.phpt'],
	['xmlwriter', '010.phpt'],
	['xmlwriter', '011.phpt'],
	['xmlwriter', '012.phpt'],
	['xmlwriter', 'bug39504.phpt'],
	['xmlwriter', 'bug41287.phpt'],
	['xmlwriter', 'bug41326.phpt'],
	['xmlwriter', 'bug48204.phpt'],
	['xmlwriter', 'bug71536.phpt'],
	['xmlwriter', 'bug79344.phpt'],
	['xmlwriter', 'OO_001.phpt'],
	['xmlwriter', 'OO_002.phpt'],
	['xmlwriter', 'OO_003.phpt'],
	['xmlwriter', 'OO_004.phpt'],
	['xmlwriter', 'OO_005.phpt'],
	['xmlwriter', 'OO_006.phpt'],
	['xmlwriter', 'OO_007.phpt'],
	['xmlwriter', 'OO_008.phpt'],
	['xmlwriter', 'OO_009.phpt'],
	['xmlwriter', 'OO_010.phpt'],
	['xmlwriter', 'OO_011.phpt'],
	['xmlwriter', 'OO_012.phpt'],
	['xmlwriter', 'OO_013.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_001.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_003.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_004.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_005.phpt'],
	['xmlwriter', 'xmlwriter_write_attribute_ns_basic_001.phpt'],
	['xmlwriter', 'xmlwriter_write_dtd_basic_001.phpt'],
	['zlib', '003.phpt'],
	['zlib', '004-mb.phpt'],
	['zlib', '004.phpt'],
	['zlib', '006.phpt'],
	['zlib', '007.phpt'],
	['zlib', '008.phpt'],
	['zlib', 'bug48725.phpt'],
	['zlib', 'bug48725_2.phpt'],
	['zlib', 'bug61287.phpt'],
	['zlib', 'bug61443.phpt'],
	['zlib', 'bug61820.phpt'],
	['zlib', 'bug71417.phpt'],
	['zlib', 'bug73944.phpt'],
	['zlib', 'bug74240.phpt'],
	['zlib', 'bug75273.phpt'],
	['zlib', 'bug75299.phpt'],
	['zlib', 'bug_34821.phpt'],
	['zlib', 'bug_52944.phpt'],
	['zlib', 'deflate_add_basic.phpt'],
	['zlib', 'deflate_add_buffer_full.phpt'],
	['zlib', 'deflate_add_error.phpt'],
	['zlib', 'deflate_init_error.phpt'],
	['zlib', 'deflate_init_reuse.phpt'],
	['zlib', 'dictionary_usage.phpt'],
	['zlib', 'gzclose_basic.phpt'],
	['zlib', 'gzcompress_error1.phpt'],
	['zlib', 'gzcompress_variation1.phpt'],
	['zlib', 'gzdeflate_error1.phpt'],
	['zlib', 'gzdeflate_variation1.phpt'],
	['zlib', 'gzencode_error1.phpt'],
	['zlib', 'gzeof_basic.phpt'],
	['zlib', 'gzeof_variation1.phpt'],
	['zlib', 'gzfile_basic.phpt'],
	['zlib', 'gzfile_basic2.phpt'],
	['zlib', 'gzfile_variation12.phpt'],
	['zlib', 'gzfile_variation15.phpt'],
	['zlib', 'gzfile_variation4.phpt'],
	['zlib', 'gzfile_variation5.phpt'],
	['zlib', 'gzfile_variation7.phpt'],
	['zlib', 'gzfile_variation9.phpt'],
	['zlib', 'gzfilegzreadfile.phpt'],
	['zlib', 'gzgets_basic.phpt'],
	['zlib', 'gzinflate-bug42663.phpt'],
	['zlib', 'gzinflate_error1.phpt'],
	['zlib', 'gzinflate_length.phpt'],
	['zlib', 'gzopen_basic.phpt'],
	['zlib', 'gzopen_basic2.phpt'],
	['zlib', 'gzopen_variation4.phpt'],
	['zlib', 'gzopen_variation5.phpt'],
	['zlib', 'gzopen_variation6.phpt'],
	['zlib', 'gzopen_variation7.phpt'],
	['zlib', 'gzopen_variation8.phpt'],
	['zlib', 'gzopen_variation9.phpt'],
	['zlib', 'gzpassthru_basic.phpt'],
	['zlib', 'gzputs_basic.phpt'],
	['zlib', 'gzread_basic.phpt'],
	['zlib', 'gzread_error2.phpt'],
	['zlib', 'gzread_variation1.phpt'],
	['zlib', 'gzreadgzwrite.phpt'],
	['zlib', 'gzreadgzwriteplain.phpt'],
	['zlib', 'gzrewind_basic.phpt'],
	['zlib', 'gzrewind_basic2.phpt'],
	['zlib', 'gzrewind_variation1.phpt'],
	['zlib', 'gzseek_basic.phpt'],
	['zlib', 'gzseek_basic2.phpt'],
	['zlib', 'gzseek_variation1.phpt'],
	['zlib', 'gzseek_variation2.phpt'],
	['zlib', 'gzseek_variation3.phpt'],
	['zlib', 'gzseek_variation4.phpt'],
	['zlib', 'gzseek_variation5.phpt'],
	['zlib', 'gzseek_variation6.phpt'],
	['zlib', 'gzseek_variation7.phpt'],
	['zlib', 'gztell_basic.phpt'],
	['zlib', 'gztell_basic2.phpt'],
	['zlib', 'gzuncompress_basic1.phpt'],
	['zlib', 'gzuncompress_error1.phpt'],
	['zlib', 'gzwrite_basic.phpt'],
	['zlib', 'gzwrite_error2.phpt'],
	['zlib', 'gzwrite_variation1.phpt'],
	['zlib', 'inflate_add_error.phpt'],
	['zlib', 'inflate_get_read_len.phpt'],
	['zlib', 'inflate_get_status.phpt'],
	['zlib', 'inflate_init_error.phpt'],
	['zlib', 'inflate_init_reuse.phpt'],
	['zlib', 'ob_002.phpt'],
	['zlib', 'readgzfile_basic.phpt'],
	['zlib', 'readgzfile_basic2.phpt'],
	['zlib', 'readgzfile_variation12.phpt'],
	['zlib', 'readgzfile_variation15.phpt'],
	['zlib', 'readgzfile_variation4.phpt'],
	['zlib', 'readgzfile_variation5.phpt'],
	['zlib', 'readgzfile_variation7.phpt'],
	['zlib', 'readgzfile_variation9.phpt'],
	['zlib', 'zlib_filter_deflate.phpt'],
	['zlib', 'zlib_filter_deflate2.phpt'],
	['zlib', 'zlib_filter_inflate.phpt'],
	['zlib', 'zlib_get_coding_type_basic.phpt'],
	['zlib', 'zlib_get_coding_type_br.phpt'],
	['zlib', 'zlib_scheme_copy_basic.phpt'],
	['zlib', 'zlib_scheme_copy_variation1.phpt'],
	['zlib', 'zlib_scheme_copy_variation2.phpt'],
	['zlib', 'zlib_scheme_dir_basic.phpt'],
	['zlib', 'zlib_scheme_file_basic.phpt'],
	['zlib', 'zlib_scheme_file_get_contents_basic.phpt'],
	['zlib', 'zlib_scheme_file_put_contents_basic.phpt'],
	['zlib', 'zlib_scheme_file_read_file_basic.phpt'],
	['zlib', 'zlib_scheme_fopen_basic.phpt'],
	['zlib', 'zlib_scheme_fopen_variation1.phpt'],
	['zlib', 'zlib_scheme_rename_basic.phpt'],
	['zlib', 'zlib_scheme_stat_basic.phpt'],
	['zlib', 'zlib_scheme_stat_basic2.phpt'],
	['zlib', 'zlib_scheme_unlink_basic.phpt'],
	['zlib', 'zlib_wrapper_fflush_basic.phpt'],
	['zlib', 'zlib_wrapper_flock_basic.phpt'],
	['zlib', 'zlib_wrapper_fstat_basic.phpt'],
	['zlib', 'zlib_wrapper_ftruncate_basic.phpt'],
	['zlib', 'zlib_wrapper_meta_data_basic.phpt'],
	['sqlite3', 'bug47159.phpt'],
	['sqlite3', 'bug66550.phpt'],
	['sqlite3', 'bug68760.phpt'],
	['sqlite3', 'bug69972.phpt'],
	['sqlite3', 'bug70628.phpt'],
	['sqlite3', 'bug71049.phpt'],
	['sqlite3', 'bug72571.phpt'],
	['sqlite3', 'bug72668.phpt'],
	['sqlite3', 'bug73333.phpt'],
	['sqlite3', 'bug76665.phpt'],
	['sqlite3', 'bug77051.phpt'],
	['sqlite3', 'bug79294.phpt'],
	['sqlite3', 'exception_from_toString.phpt'],
	['sqlite3', 'gh11451.phpt'],
	['sqlite3', 'gh11878.phpt'],
	['sqlite3', 'sqlite3_01_open-mb.phpt'],
	['sqlite3', 'sqlite3_02_create.phpt'],
	['sqlite3', 'sqlite3_02_open.phpt'],
	['sqlite3', 'sqlite3_03_insert.phpt'],
	['sqlite3', 'sqlite3_04_update.phpt'],
	['sqlite3', 'sqlite3_05_delete.phpt'],
	['sqlite3', 'sqlite3_06_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_07_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_08_udf.phpt'],
	['sqlite3', 'sqlite3_09_blob_bound_param.phpt'],
	['sqlite3', 'sqlite3_10_bound_value_name.phpt'],
	['sqlite3', 'sqlite3_12_unfinalized_stmt_cleanup.phpt'],
	['sqlite3', 'sqlite3_13_skip_all_cleanup.phpt'],
	['sqlite3', 'sqlite3_14_querysingle.phpt'],
	['sqlite3', 'sqlite3_16_select_no_results.phpt'],
	['sqlite3', 'sqlite3_17_version.phpt'],
	['sqlite3', 'sqlite3_18_changes.phpt'],
	['sqlite3', 'sqlite3_19_columninfo.phpt'],
	['sqlite3', 'sqlite3_20_error.phpt'],
	['sqlite3', 'sqlite3_23_escape_string.phpt'],
	['sqlite3', 'sqlite3_24_last_insert_rowid.phpt'],
	['sqlite3', 'sqlite3_25_create_aggregate.phpt'],
	['sqlite3', 'sqlite3_26_reset_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_27_reset_prepared_stmt_result.phpt'],
	['sqlite3', 'sqlite3_28_clear_bindings.phpt'],
	['sqlite3', 'sqlite3_29_createfunction.phpt'],
	['sqlite3', 'sqlite3_30_blobopen.phpt'],
	['sqlite3', 'sqlite3_31_changes.phpt'],
	['sqlite3', 'sqlite3_33_createAggregate_notcallable.phpt'],
	['sqlite3', 'sqlite3_33_reset.phpt'],
	['sqlite3', 'sqlite3_36_create_collation.phpt'],
	['sqlite3', 'sqlite3_38_backup.phpt'],
	['sqlite3', 'sqlite3_38_extended_error.phpt'],
	['sqlite3', 'sqlite3_39_toggleExtended.phpt'],
	['sqlite3', 'sqlite3_40_setauthorizer.phpt'],
	['sqlite3', 'sqlite3_bind_bug68849.phpt'],
	['sqlite3', 'sqlite3_blob_bind_resource.phpt'],
	['sqlite3', 'sqlite3_bound_value_at_name.phpt'],
	['sqlite3', 'sqlite3_busyTimeout.phpt'],
	['sqlite3', 'sqlite3_enable_exceptions.phpt'],
	['sqlite3', 'sqlite3_open_empty_string.phpt'],
	['sqlite3', 'sqlite3_prepare_001.phpt'],
	['sqlite3', 'sqlite3_prepare_faultystmt.phpt'],
	['sqlite3', 'sqlite3_prepare_with_empty_string.phpt'],
	['sqlite3', 'sqlite3_trampoline_create_aggregate.phpt'],
	['sqlite3', 'sqlite3_trampoline_create_collation.phpt'],
	['sqlite3', 'sqlite3_trampoline_createfunction.phpt'],
	['sqlite3', 'sqlite3_trampoline_setauthorizer.phpt'],
	['sqlite3', 'sqlite3stmt_getsql.phpt'],
	['sqlite3', 'sqlite3stmt_paramCount_basic.phpt'],
	['tidy', '002.phpt'],
	['tidy', '005-mb.phpt'],
	['tidy', '005.phpt'],
	['tidy', '007.phpt'],
	['tidy', '008.phpt'],
	['tidy', '009.phpt'],
	['tidy', '010.phpt'],
	['tidy', '011.phpt'],
	['tidy', '012.phpt'],
	['tidy', '013.phpt'],
	['tidy', '014.phpt'],
	['tidy', '015.phpt'],
	['tidy', '016.phpt'],
	['tidy', '018.phpt'],
	['tidy', '019.phpt'],
	['tidy', '023.phpt'],
	['tidy', '024.phpt'],
	['tidy', '025.phpt'],
	['tidy', '027.phpt'],
	['tidy', '028.phpt'],
	['tidy', '029.phpt'],
	['tidy', '030.phpt'],
	['tidy', '031.phpt'],
	['tidy', '032.phpt'],
	['tidy', '033.phpt'],
	['tidy', '034.phpt'],
	['tidy', '035.phpt'],
	['tidy', '036.phpt'],
	['tidy', 'bug54682.phpt'],
	['tidy', 'bug77040.phpt'],
	['tidy', 'bug77594.phpt'],
	['tidy', 'bug_50558.phpt'],
	['tidy', 'gh12980.phpt'],
	['tidy', 'parsing_inexistent_file.phpt'],
	['tidy', 'tidy_error.phpt'],
	['tidy', 'tidy_error1.phpt'],
	['tidy', 'uninitialized.phpt'],
	['iconv', 'bug48289.phpt'],
	['iconv', 'bug52211.phpt'],
	['iconv', 'bug52941.phpt'],
	['iconv', 'bug53891.phpt'],
	['iconv', 'bug55146.phpt'],
	['iconv', 'bug60494.phpt'],
	['iconv', 'bug63839.phpt'],
	['iconv', 'bug66828.phpt'],
	['iconv', 'bug68180.phpt'],
	['iconv', 'bug69840.phpt'],
	['iconv', 'bug72320.phpt'],
	['iconv', 'bug74230.phpt'],
	['iconv', 'bug76249.phpt'],
	['iconv', 'bug77147.phpt'],
	['iconv', 'bug78069.phpt'],
	['iconv', 'bug79200.phpt'],
	['iconv', 'gh7980.phpt'],
	['iconv', 'iconv-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv003.phpt'],
	['iconv', 'iconv_basic.phpt'],
	['iconv', 'iconv_default_charset.phpt'],
	['iconv', 'iconv_encoding_basic.phpt'],
	['iconv', 'iconv_get_encoding_basic.phpt'],
	['iconv', 'iconv_ini_encoding.phpt'],
	['iconv', 'iconv_mime_decode-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_mime_decode.phpt'],
	['iconv', 'iconv_mime_decode_headers-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_mime_decode_headers.phpt'],
	['iconv', 'iconv_mime_encode_001.phpt'],
	['iconv', 'iconv_set_encoding-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_stream_filter.phpt'],
	['iconv', 'iconv_stream_filter_delimiter.phpt'],
	['iconv', 'iconv_strlen-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strlen_basic.phpt'],
	['iconv', 'iconv_strlen_error2.phpt'],
	['iconv', 'iconv_strpos-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strpos_basic.phpt'],
	['iconv', 'iconv_strpos_error2.phpt'],
	['iconv', 'iconv_strpos_error_001.phpt'],
	['iconv', 'iconv_strpos_variation5.phpt'],
	['iconv', 'iconv_strrpos-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strrpos_basic.phpt'],
	['iconv', 'iconv_strrpos_error2.phpt'],
	['iconv', 'iconv_substr-charset-length-cve-2007-4783.phpt'],
	['iconv', 'iconv_substr_basic.phpt'],
	['iconv', 'iconv_substr_error2.phpt'],
	['iconv', 'iconv_substr_out_of_bounds.phpt'],
	['iconv', 'ob_iconv_handler-charset-length-cve-2007-4840.phpt']
];

const attachOutput = php => {
	let stdOut = '';
	let stdErr = '';

	php.addEventListener('output', event => event.detail.forEach(line => void (stdOut += line)));
	php.addEventListener('error', event => event.detail.forEach(line => void (stdErr += line)));

	return {
		stdOut: () => stdOut
		, stdErr: () => stdErr
	};
};

test('runs a CLI script in Node', async () => {
	const php = new PhpCliNode(nodeRuntimeOptions({
		runtime: 'cli',
		code: 'echo "Hello, World!";'
		, version
	}));
	const {stdOut, stdErr} = attachOutput(php);

	await php.binary;

	const exitCode = await php.run();

	assert.equal(exitCode, 0);
	assert.equal(stdOut(), 'Hello, World!');
	assert.equal(stdErr(), '');
});

test(`loads the requested CLI runtime version (${version})`, async () => {
	const php = new PhpCliNode(nodeRuntimeOptions({
		runtime: 'cli',
		code: 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;'
		, version
	}));
	const {stdOut, stdErr} = attachOutput(php);

	await php.binary;

	const exitCode = await php.run();

	assert.equal(exitCode, 0);
	assert.equal(stdOut(), version);
	assert.equal(stdErr(), '');
});

for(const phptName of directCliPhpts)
{
	test(`runs core PHPT ${phptName} directly in CLI Node (${version})`, async () => {
		await runCliPhpt({
			phptFile: phpt(phptName),
			version
		});
	});
}

for(const [extensionName, phptName] of directCliExtensionPhpts)
{
	test(`runs ${extensionName} PHPT ${phptName} directly in CLI Node (${version})`, async () => {
		await runCliPhpt({
			phptFile: extPhpt(extensionName, phptName),
			version
		});
	});
}
