import { strict as assert } from 'node:assert';
import fs from 'node:fs';
import { test } from 'node:test';
import path from 'node:path';
import url from 'node:url';

import { PhpCliNode } from '../../packages/php-cli-wasm/PhpCliNode.mjs';
import { nodeRuntimeOptions } from '../lib/node-runtime-options.mjs';
import { runCliPhpt } from '../lib/phpt.mjs';

const version = process.env.PHP_VERSION ?? '8.4';
const here = path.dirname(url.fileURLToPath(import.meta.url));
const phpt = name => path.resolve(here, `../../third_party/php${version}-src/tests/lang/${name}.phpt`);
const extPhpt = (extension, name) => path.resolve(here, `../../third_party/php${version}-src/ext/${extension}/tests/${name}`);
const [phpMajor, phpMinor] = version.split('.').map(Number);
const atLeast = (major, minor) => phpMajor > major || (phpMajor === major && phpMinor >= minor);
const simplexmlImportDomPhpts = atLeast(8, 4)
	? ['simplexml_import_new_dom.phpt', 'simplexml_import_old_dom.phpt']
	: ['simplexml_import_dom.phpt'];
const registerNodeClassPhpt = atLeast(8, 4)
	? 'register_node_class.phpt'
	: 'regsiter_node_class.phpt';
const removedZlibPhptsInPhp85 = [
	['zlib', '004-mb.phpt'],
	['zlib', '004.phpt'],
	['zlib', '007.phpt'],
	['zlib', 'gzfile_variation12.phpt'],
	['zlib', 'gzfile_variation4.phpt'],
	['zlib', 'gzfile_variation5.phpt'],
	['zlib', 'gzfile_variation9.phpt'],
	['zlib', 'readgzfile_variation12.phpt'],
	['zlib', 'readgzfile_variation4.phpt'],
	['zlib', 'readgzfile_variation5.phpt'],
	['zlib', 'readgzfile_variation9.phpt'],
];
const directCliPhpts = [
	'001',
	'002',
	'003',
	'004',
	'005',
	'006',
	'007',
	'008',
	'009',
	'010',
	'011',
	'012',
	'013',
	'014',
	'015',
	'016',
	'017',
	'018',
	'019',
	'020',
	'021',
	'022',
	'023',
	'026',
	'027',
	'028',
	'030',
	'032',
	'033',
	'035',
	'036',
	'037',
	'038',
	'039',
	'040',
	'041',
	'042',
	'043',
	'044',
	'array_shortcut_001',
	'array_shortcut_002',
	'array_shortcut_003',
	'array_shortcut_005',
	'bison1',
	'bug18872',
	'bug19566',
	'bug19943',
	'bug20175',
	'bug21094',
	'bug21600',
	'bug21669',
	'bug21820',
	'bug21849',
	'bug21961',
	'bug22231',
	'bug22510',
	'bug22592',
	'bug23279',
	'bug23384',
	'bug23489',
	'bug23524',
	'bug23584',
	'bug23624',
	'bug24054',
	'bug24396',
	'bug24436',
	'bug24499',
	'bug24573',
	'bug24640',
	'bug24652',
	'bug24658',
	'bug24783',
	'bug24908',
	'bug24951',
	'bug25547',
	'bug25652',
	'bug25922',
	'bug26182',
	'bug26696',
	'bug26866',
	'bug26869',
	'bug27354',
	'bug27439',
	'bug27443',
	'bug27535',
	'bug28213',
	'bug28800',
	'bug29566',
	'bug29893',
	'bug29944',
	'bug30578',
	'bug30726',
	'bug30862',
	'bug32828',
	'bug32924',
	'bug35176',
	'bug35382',
	'bug43958',
	'bug44654',
	'bug44827',
	'bug55754',
	'bug71897',
	'bug73172',
	'bug73329',
	'bug7515',
	'catchable_error_001',
	'catchable_error_002',
	'comments',
	'comments2',
	'compare_objects_basic1',
	'compare_objects_basic2',
	'empty_variation',
	'engine_assignExecutionOrder_001',
	'engine_assignExecutionOrder_002',
	'engine_assignExecutionOrder_003',
	'engine_assignExecutionOrder_004',
	'engine_assignExecutionOrder_005',
	'engine_assignExecutionOrder_006',
	'engine_assignExecutionOrder_007',
	'engine_assignExecutionOrder_008',
	'engine_assignExecutionOrder_009',
	'error_2_exception_001',
	'execution_order',
	'foreach_with_object_001',
	'foreach_with_references_001',
	'foreachLoop.001',
	'foreachLoop.002',
	'foreachLoop.003',
	'foreachLoop.004',
	'foreachLoop.005',
	'foreachLoop.006',
	'foreachLoop.009',
	'foreachLoop.010',
	'foreachLoop.011',
	'foreachLoop.012',
	'foreachLoop.013',
	'foreachLoop.014',
	'foreachLoop.015',
	'foreachLoop.016',
	'foreachLoop.017',
	'foreachLoopIterator.001',
	'foreachLoopIterator.002',
	'foreachLoopIteratorAggregate.001',
	'foreachLoopIteratorAggregate.002',
	'foreachLoopIteratorAggregate.003',
	'foreachLoopIteratorAggregate.004',
	'foreachLoopObjects.001',
	'foreachLoopObjects.002',
	'foreachLoopObjects.003',
	'foreachLoopObjects.004',
	'foreachLoopObjects.005',
	'foreachLoopObjects.006',
	'func_get_arg_variation',
	'func_get_arg.001',
	'func_get_arg.002',
	'func_get_arg.003',
	'func_get_arg.004',
	'func_get_arg.005',
	'func_get_args.001',
	'func_get_args.002',
	'func_get_args.003',
	'func_get_args.004',
	'func_num_args.001',
	'func_num_args.002',
	'func_num_args.003',
	'func_num_args.004',
	'include_variation1',
	'include_variation2',
	'include_variation3',
	'invalid_octal',
	'passByReference_001',
	'passByReference_002',
	'passByReference_003',
	'passByReference_004',
	'passByReference_005',
	'passByReference_006',
	'passByReference_007',
	'passByReference_008',
	'passByReference_009',
	'passByReference_010',
	'passByReference_012',
	'returnByReference.001',
	'returnByReference.002',
	'returnByReference.003',
	'returnByReference.004',
	'returnByReference.005',
	'returnByReference.006',
	'returnByReference.007',
	'returnByReference.008',
	'returnByReference.009',
	'short_tags.001',
	'short_tags.002',
	'short_tags.004',
	'static_basic_001',
	'static_basic_002',
	'static_variation_001',
	'static_variation_002',
	'string_decimals_001',
	'syntax_errors',
	'this_assignment',
	'throw_variation_001',
	'type_hints_001',
	'type_hints_002',
	'type_hints_003',
	'zend_throw_exception_001',
	'operators/add_variationStr',
	'operators/bitwiseAnd_variationStr',
	'operators/bitwiseNot_variationStr',
	'operators/bitwiseOr_variationStr',
	'operators/bitwiseShiftLeft_variationStr',
	'operators/bitwiseShiftLeft_variationStr2',
	'operators/bitwiseShiftRight_variationStr',
	'operators/bitwiseShiftRight_variationStr2',
	'operators/bitwiseXor_variationStr',
	'operators/coalesce',
	'operators/divide_variationStr',
	'operators/modulus_variationStr',
	'operators/multiply_variationStr',
	'operators/nan-comparison-false',
	'operators/negate_variationStr',
	'operators/operator_equals_basic',
	'operators/operator_gt_basic',
	'operators/operator_gt_or_equal_basic',
	'operators/operator_gt_variation',
	'operators/operator_identical_basic',
	'operators/operator_identical_recusion-01',
	'operators/operator_lt_basic',
	'operators/operator_lt_or_equal_basic',
	'operators/operator_lt_variation',
	'operators/operator_notequals_basic',
	'operators/operator_notidentical_basic',
	'operators/operator_spaceship_basic',
	'operators/overloaded_property_ref',
	'operators/postdec_variationStr',
	'operators/postinc_variationStr',
	'operators/predec_variationStr',
	'operators/preinc_variationStr',
	'operators/subtract_variationStr',
	'string/unicode_escape',
	'string/unicode_escape_empty',
	'string/unicode_escape_incomplete',
	'string/unicode_escape_large_codepoint',
	'string/unicode_escape_legacy',
	'string/unicode_escape_sign',
	'string/unicode_escape_sign2',
	'string/unicode_escape_surrogates',
	'string/unicode_escape_whitespace',
];
const directCliExtensionPhpts = [
	['simplexml', '000.phpt'],
	['simplexml', '001-mb.phpt'],
	['simplexml', '001.phpt'],
	['simplexml', '002.phpt'],
	['simplexml', '003.phpt'],
	['simplexml', '004.phpt'],
	['simplexml', '005.phpt'],
	['simplexml', '006.phpt'],
	['simplexml', '007.phpt'],
	['simplexml', '008.phpt'],
	['simplexml', '009.phpt'],
	['simplexml', '009b.phpt'],
	['simplexml', '010.phpt'],
	['simplexml', '011.phpt'],
	['simplexml', '012.phpt'],
	['simplexml', '013.phpt'],
	['simplexml', '014.phpt'],
	['simplexml', '014a.phpt'],
	['simplexml', '014b.phpt'],
	['simplexml', '015.phpt'],
	['simplexml', '016.phpt'],
	['simplexml', '016a.phpt'],
	['simplexml', '017.phpt'],
	['simplexml', '018.phpt'],
	['simplexml', '019.phpt'],
	['simplexml', '020.phpt'],
	['simplexml', '021.phpt'],
	['simplexml', '022.phpt'],
	['simplexml', '023.phpt'],
	['simplexml', '024.phpt'],
	['simplexml', '025.phpt'],
	['simplexml', '026.phpt'],
	['simplexml', '027.phpt'],
	['simplexml', '028.phpt'],
	['simplexml', '029.phpt'],
	['simplexml', '030.phpt'],
	['simplexml', '031.phpt'],
	['simplexml', '032.phpt'],
	['simplexml', '033.phpt'],
	['simplexml', '034.phpt'],
	['simplexml', '035.phpt'],
	['simplexml', '036.phpt'],
	['simplexml', '037.phpt'],
	['simplexml', '038.phpt'],
	['simplexml', 'bug12170.phpt'],
	['simplexml', 'bug24392.phpt'],
	['simplexml', 'bug26976.phpt'],
	['simplexml', 'bug27010.phpt'],
	['simplexml', 'bug35785.phpt'],
	['simplexml', 'bug36611.phpt'],
	['simplexml', 'bug37076_1.phpt'],
	['simplexml', 'bug37076.phpt'],
	['simplexml', 'bug37386.phpt'],
	['simplexml', 'bug38347.phpt'],
	['simplexml', 'bug38354.phpt'],
	['simplexml', 'bug38406.phpt'],
	['simplexml', 'bug38424.phpt'],
	['simplexml', 'bug39662.phpt'],
	['simplexml', 'bug39760.phpt'],
	['simplexml', 'bug40451.phpt'],
	['simplexml', 'bug41175.phpt'],
	['simplexml', 'bug41582.phpt'],
	['simplexml', 'bug41861.phpt'],
	['simplexml', 'bug41867.phpt'],
	['simplexml', 'bug41947.phpt'],
	['simplexml', 'bug42259.phpt'],
	['simplexml', 'bug42369.phpt'],
	['simplexml', 'bug43221.phpt'],
	['simplexml', 'bug44478.phpt'],
	['simplexml', 'bug45553.phpt'],
	['simplexml', 'bug46003.phpt'],
	['simplexml', 'bug46047.phpt'],
	['simplexml', 'bug46048.phpt'],
	['simplexml', 'bug48601.phpt'],
	['simplexml', 'bug51615.phpt'],
	['simplexml', 'bug52751.phpt'],
	['simplexml', 'bug53033.phpt'],
	['simplexml', 'bug54973.phpt'],
	['simplexml', 'bug61335.phpt'],
	['simplexml', 'bug62328.phpt'],
	['simplexml', 'bug62639.phpt'],
	['simplexml', 'bug63575.phpt'],
	['simplexml', 'bug66084_0.phpt'],
	['simplexml', 'bug66084_1.phpt'],
	['simplexml', 'bug67116.phpt'],
	['simplexml', 'bug67572.phpt'],
	['simplexml', 'bug69169.phpt'],
	['simplexml', 'bug69491.phpt'],
	['simplexml', 'bug72588.phpt'],
	['simplexml', 'bug72957.phpt'],
	['simplexml', 'bug72971_2.phpt'],
	['simplexml', 'bug72971.phpt'],
	['simplexml', 'bug75245.phpt'],
	['simplexml', 'bug76712.phpt'],
	['simplexml', 'bug81325.phpt'],
	['simplexml', 'current_error.phpt'],
	['simplexml', 'feature55218.phpt'],
	['simplexml', 'foreach_by_reference.phpt'],
	['simplexml', 'get_prop_address_not_initialized.phpt'],
	['simplexml', 'gh10200.phpt'],
	['simplexml', 'gh10983.phpt'],
	['simplexml', 'gh12167.phpt'],
	['simplexml', 'gh12169.phpt'],
	['simplexml', 'gh12223.phpt'],
	['simplexml', 'gh12929.phpt'],
	['simplexml', 'gh14638.phpt'],
	['simplexml', 'key_error.phpt'],
	['simplexml', 'profile11.phpt'],
	['simplexml', 'profile12.phpt'],
	['simplexml', 'profile13.phpt'],
	['simplexml', 'profile01.phpt'],
	['simplexml', 'profile02.phpt'],
	['simplexml', 'profile03.phpt'],
	['simplexml', 'profile04.phpt'],
	['simplexml', 'profile05.phpt'],
	['simplexml', 'profile06.phpt'],
	['simplexml', 'profile07.phpt'],
	['simplexml', 'profile08.phpt'],
	['simplexml', 'profile09.phpt'],
	['simplexml', 'profile10.phpt'],
	...simplexmlImportDomPhpts.map(name => ['simplexml', name]),
	['simplexml', 'simplexml_load_file.phpt'],
	['simplexml', 'simplexml_uninitialized.phpt'],
	['simplexml', 'SimpleXMLElement_addAttribute_basic.phpt'],
	['simplexml', 'SimpleXMLElement_addAttribute_required_attribute_name.phpt'],
	['simplexml', 'SimpleXMLElement_getDocNamespaces.phpt'],
	['simplexml', 'SimpleXMLElement_xpath.phpt'],
	['simplexml', 'sxe_001.phpt'],
	['simplexml', 'sxe_002.phpt'],
	['simplexml', 'sxe_003.phpt'],
	['simplexml', 'sxe_004.phpt'],
	['simplexml', 'sxe_005.phpt'],
	['dom', 'DOMDocument_loadHTMLfile_variation1.phpt'],
	['dom', 'DOM4_ChildNode_wrong_document.phpt'],
	['dom', 'DOM4_DOMNode_ElementSiblings.phpt'],
	['dom', 'DOM4_DOMNode_after.phpt'],
	['dom', 'DOM4_DOMNode_after_ns.phpt'],
	['dom', 'DOM4_DOMNode_append_ns.phpt'],
	['dom', 'DOM4_DOMNode_before.phpt'],
	['dom', 'DOM4_DOMNode_before_ns.phpt'],
	['dom', 'DOM4_DOMNode_prepend_ns.phpt'],
	['dom', 'DOM4_DOMNode_remove.phpt'],
	['dom', 'DOM4_DOMNode_removeDanglingElement.phpt'],
	['dom', 'DOM4_DOMNode_replaceWith.phpt'],
	['dom', 'DOM4_ParentNode.phpt'],
	['dom', 'DOM4_ParentNode_Fragment.phpt'],
	['dom', 'DOM4_ParentNode_append.phpt'],
	['dom', 'DOM4_ParentNode_append_invalidtypes.phpt'],
	['dom', 'DOM4_ParentNode_append_with_attributes.phpt'],
	['dom', 'DOM4_ParentNode_append_wrong_document.phpt'],
	['dom', 'DOM4_ParentNode_prepend.phpt'],
	['dom', 'DOMAttr_construct_error_001.phpt'],
	['dom', 'DOMAttr_name_basic_001.phpt'],
	['dom', 'DOMAttr_ownerElement_error_001.phpt'],
	['dom', 'DOMAttr_value_basic_001.phpt'],
	['dom', 'DOMAttr_value_basic_002.phpt'],
	['dom', 'DOMCDATASection_construct_error_001.phpt'],
	['dom', 'DOMCharacterData_appendData_basic.phpt'],
	['dom', 'DOMCharacterData_data_basic_002.phpt'],
	['dom', 'DOMCharacterData_data_error_002.phpt'],
	['dom', 'DOMCharacterData_deleteData_basic_001.phpt'],
	['dom', 'DOMCharacterData_deleteData_error_002.phpt'],
	['dom', 'DOMCharacterData_length_error_001.phpt'],
	['dom', 'DOMCharacterData_replaceWith_self.phpt'],
	['dom', 'DOMCharacterData_substringData_basic_001.phpt'],
	['dom', 'DOMChildNode_methods_without_parent.phpt'],
	['dom', 'DOMComment_appendData_basic.phpt'],
	['dom', 'DOMComment_appendData_basic_Sullivan.phpt'],
	['dom', 'DOMComment_construct_basic_001.phpt'],
	['dom', 'DOMComment_construct_error_001.phpt'],
	['dom', 'DOMComment_insertData_basic.phpt'],
	['dom', 'DOMComment_insertData_error1.phpt'],
	['dom', 'DOMComment_insertData_error2.phpt'],
	['dom', 'DOMComment_replaceData_basic.phpt'],
	['dom', 'DOMComment_replaceData_error1.phpt'],
	['dom', 'DOMComment_replaceData_error2.phpt'],
	['dom', 'DOMDocumentFragment_appendXML_basic_001.phpt'],
	['dom', 'DOMDocumentFragment_appendXML_error_002.phpt'],
	['dom', 'DOMDocumentFragment_appendXML_error_003.phpt'],
	['dom', 'DOMDocumentFragment_appendXML_hasChildNodes_basic.phpt'],
	['dom', 'DOMDocumentFragment_construct_basic_001.phpt'],
	['dom', 'DOMDocumentFragment_construct_error_001.phpt'],
	['dom', 'DOMDocumentType_basic_001.phpt'],
	['dom', 'DOMDocumentType_entities_error_001.phpt'],
	['dom', 'DOMDocumentType_internalSubset_error_001.phpt'],
	['dom', 'DOMDocumentType_name_error_001.phpt'],
	['dom', 'DOMDocumentType_notations_error_001.phpt'],
	['dom', 'DOMDocumentType_publicId_basic_001.phpt'],
	['dom', 'DOMDocumentType_publicId_error_001.phpt'],
	['dom', 'DOMDocumentType_systemId_basic_001.phpt'],
	['dom', 'DOMDocumentType_systemId_error_001.phpt'],
	['dom', 'DOMDocument_adoptNode.phpt'],
	['dom', 'DOMDocument_adoptNode_attribute_references.phpt'],
	['dom', 'DOMDocument_config_basic.phpt'],
	['dom', 'DOMDocument_createAttribute_basic.phpt'],
	['dom', 'DOMDocument_createAttribute_error.phpt'],
	['dom', 'DOMDocument_createAttribute_error1.phpt'],
	['dom', 'DOMDocument_createAttribute_variation.phpt'],
	['dom', 'DOMDocument_createEntityReference_basic.phpt'],
	['dom', 'DOMDocument_createEntityReference_error1.phpt'],
	['dom', 'DOMDocument_createProcessingInstruction_basic.phpt'],
	['dom', 'DOMDocument_createProcessingInstruction_error.phpt'],
	['dom', 'DOMDocument_documentURI_basic.phpt'],
	['dom', 'DOMDocument_encoding_basic.phpt'],
	['dom', 'DOMDocument_getElementsByTagNameNS_match_any_namespace.phpt'],
	['dom', 'DOMDocument_getElementsByTagName_liveness.phpt'],
	['dom', 'DOMDocument_getElementsByTagName_liveness_simplexml.phpt'],
	['dom', 'DOMDocument_getElementsByTagName_liveness_tree_walk.phpt'],
	['dom', 'DOMDocument_getElementsByTagName_liveness_write_properties.phpt'],
	['dom', 'DOMDocument_implementationRead_basic.phpt'],
	['dom', 'DOMDocument_importNode_attribute_prefix_conflict.phpt'],
	['dom', 'DOMDocument_item_cache_invalidation.phpt'],
	['dom', 'DOMDocument_json_encode.phpt'],
	['dom', 'DOMDocument_length_cache_invalidation.phpt'],
	['dom', 'DOMDocument_liveness_caching_invalidation.phpt'],
	['dom', 'DOMDocument_loadHTML_basic.phpt'],
	['dom', 'DOMDocument_loadHTML_error2.phpt'],
	['dom', 'DOMDocument_loadXML_error6.phpt'],
	['dom', 'DOMDocument_load_error6.phpt'],
	['dom', 'DOMDocument_preserveWhiteSpace_basic.phpt'],
	['dom', 'DOMDocument_preserveWhiteSpace_variations.phpt'],
	['dom', 'DOMDocument_relaxNGValidateSource_basic.phpt'],
	['dom', 'DOMDocument_relaxNGValidateSource_error1.phpt'],
	['dom', 'DOMDocument_relaxNGValidateSource_error2.phpt'],
	['dom', 'DOMDocument_relaxNGValidate_basic.phpt'],
	['dom', 'DOMDocument_relaxNGValidate_error1.phpt'],
	['dom', 'DOMDocument_relaxNGValidate_error2.phpt'],
	['dom', 'DOMDocument_resolveExternals_basic.phpt'],
	['dom', 'DOMDocument_saveHTMLFile_error2.phpt'],
	['dom', 'DOMDocument_saveHTMLFile_invalid_filename.phpt'],
	['dom', 'DOMDocument_saveHTML_basic.phpt'],
	['dom', 'DOMDocument_saveHTML_error2.phpt'],
	['dom', 'DOMDocument_saveHTML_variant1.phpt'],
	['dom', 'DOMDocument_saveHTML_variant2.phpt'],
	['dom', 'DOMDocument_savexml_basic.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_addAttrs.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_basic.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_error1.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_error2.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_error3.phpt'],
	['dom', 'DOMDocument_schemaValidateSource_missingAttrs.phpt'],
	['dom', 'DOMDocument_schemaValidate_addAttrs.phpt'],
	['dom', 'DOMDocument_schemaValidate_basic.phpt'],
	['dom', 'DOMDocument_schemaValidate_error1.phpt'],
	['dom', 'DOMDocument_schemaValidate_error2.phpt'],
	['dom', 'DOMDocument_schemaValidate_error3.phpt'],
	['dom', 'DOMDocument_schemaValidate_error5.phpt'],
	['dom', 'DOMDocument_schemaValidate_error6.phpt'],
	['dom', 'DOMDocument_schemaValidate_missingAttrs.phpt'],
	['dom', 'DOMDocument_standalone_basic.phpt'],
	['dom', 'DOMDocument_strictErrorChecking_basic.phpt'],
	['dom', 'DOMDocument_strictErrorChecking_variation.phpt'],
	['dom', 'DOMDocument_validate_basic.phpt'],
	['dom', 'DOMDocument_validate_error2.phpt'],
	['dom', 'DOMDocument_validate_external_dtd.phpt'],
	['dom', 'DOMDocument_validate_on_parse_basic.phpt'],
	['dom', 'DOMDocument_validate_on_parse_variation.phpt'],
	['dom', 'DOMElement_append_hierarchy_test.phpt'],
	['dom', 'DOMElement_className.phpt'],
	['dom', 'DOMElement_getAttributeNames.phpt'],
	['dom', 'DOMElement_getElementsByTagName_without_document.phpt'],
	['dom', 'DOMElement_hasAttributes_basic.phpt'],
	['dom', 'DOMElement_id.phpt'],
	['dom', 'DOMElement_insertAdjacentElement.phpt'],
	['dom', 'DOMElement_insertAdjacentText.phpt'],
	['dom', 'DOMElement_prepend_hierarchy_test.phpt'],
	['dom', 'DOMElement_replaceChildren.phpt'],
	['dom', 'DOMElement_setAttributeNS_prefix_conflict.phpt'],
	['dom', 'DOMElement_toggleAttribute.phpt'],
	['dom', 'DOMElement_toggleAttribute_without_document.phpt'],
	['dom', 'DOMEntityReference_basic.phpt'],
	['dom', 'DOMEntityReference_error1.phpt'],
	['dom', 'DOMEntity_fields.phpt'],
	['dom', 'DOMImplementation_createDocumentType_basic.phpt'],
	['dom', 'DOMImplementation_createDocument_basic.phpt'],
	['dom', 'DOMImplementation_hasFeature_basic.phpt'],
	['dom', 'DOMNamedNodeMap_count.phpt'],
	['dom', 'DOMNamedNodeMap_edge_case_offset.phpt'],
	['dom', 'DOMNamedNodeMap_string_references.phpt'],
	['dom', 'DOMNode_C14N_basic.phpt'],
	['dom', 'DOMNode_C14N_references.phpt'],
	['dom', 'DOMNode_DOMNameSpaceNode_isConnected.phpt'],
	['dom', 'DOMNode_DOMNameSpaceNode_parentElement.phpt'],
	['dom', 'DOMNode_cloneNode_basic.phpt'],
	['dom', 'DOMNode_contains.phpt'],
	['dom', 'DOMNode_getLineNo_basic.phpt'],
	['dom', 'DOMNode_getNodePath_basic.phpt'],
	['dom', 'DOMNode_getRootNode.phpt'],
	['dom', 'DOMNode_hasChildNodes.phpt'],
	['dom', 'DOMNode_hasChildNodes_basic.phpt'],
	['dom', 'DOMNode_insertBefore.phpt'],
	['dom', 'DOMNode_insertBefore_error1.phpt'],
	['dom', 'DOMNode_issamenode_basic.phpt'],
	['dom', 'DOMNode_normalize_basic.phpt'],
	['dom', 'DOMNode_removeChild_basic.phpt'],
	['dom', 'DOMNode_removeChild_error1.phpt'],
	['dom', 'DOMNode_replaceChild_basic.phpt'],
	['dom', 'DOMNode_replaceChild_error1.phpt'],
	['dom', 'DOMNode_replaceChild_error2.phpt'],
	['dom', 'DOMParentNode_empty_argument.phpt'],
	['dom', 'DOMProcessingInstruction.phpt'],
	['dom', 'DOMText_appendData_basic.phpt'],
	['dom', 'DomNodeList_count.phpt'],
	['dom', 'ParentNode_append_fragment_text_coalesce.phpt'],
	['dom', 'bug28721.phpt'],
	['dom', 'bug28817.phpt'],
	['dom', 'bug32615.phpt'],
	['dom', 'bug34276.phpt'],
	['dom', 'bug35342.phpt'],
	['dom', 'bug35673.phpt'],
	['dom', 'bug36756.phpt'],
	['dom', 'bug37277.phpt'],
	['dom', 'bug37456.phpt'],
	['dom', 'bug38438.phpt'],
	['dom', 'bug38850.phpt'],
	['dom', 'bug38949.phpt'],
	['dom', 'bug40836.phpt'],
	['dom', 'bug41257.phpt'],
	['dom', 'bug41374.phpt'],
	['dom', 'bug42082.phpt'],
	['dom', 'bug43364.phpt'],
	['dom', 'bug44648.phpt'],
	['dom', 'bug45251.phpt'],
	['dom', 'bug46185.phpt'],
	['dom', 'bug46335.phpt'],
	['dom', 'bug46849.phpt'],
	['dom', 'bug47430.phpt'],
	['dom', 'bug47530.phpt'],
	['dom', 'bug47531_a.phpt'],
	['dom', 'bug47531_b.phpt'],
	['dom', 'bug47848.phpt'],
	['dom', 'bug47849.phpt'],
	['dom', 'bug49463.phpt'],
	['dom', 'bug49490.phpt'],
	['dom', 'bug50661.phpt'],
	['dom', 'bug52656.phpt'],
	['dom', 'bug54382.phpt'],
	['dom', 'bug54601.phpt'],
	['dom', 'bug55700.phpt'],
	['dom', 'bug61858.phpt'],
	['dom', 'bug65196.phpt'],
	['dom', 'bug66502.phpt'],
	['dom', 'bug66783.phpt'],
	['dom', 'bug67081.phpt'],
	['dom', 'bug67440.phpt'],
	['dom', 'bug67474.phpt'],
	['dom', 'bug67949.phpt'],
	['dom', 'bug69373.phpt'],
	['dom', 'bug69679.phpt'],
	['dom', 'bug69846.phpt'],
	['dom', 'bug70001.phpt'],
	['dom', 'bug70359.phpt'],
	['dom', 'bug70558.phpt'],
	['dom', 'bug73907.phpt'],
	['dom', 'bug74004.phpt'],
	['dom', 'bug74416.phpt'],
	['dom', 'bug75451.phpt'],
	['dom', 'bug77569.phpt'],
	['dom', 'bug77686.phpt'],
	['dom', 'bug78025.phpt'],
	['dom', 'bug78221.phpt'],
	['dom', 'bug78577.phpt'],
	['dom', 'bug79271.phpt'],
	['dom', 'bug79451.phpt'],
	['dom', 'bug79852.phpt'],
	['dom', 'bug79968.phpt'],
	['dom', 'bug79971_2.phpt'],
	['dom', 'bug80332_1.phpt'],
	['dom', 'bug80332_2.phpt'],
	['dom', 'bug80600.phpt'],
	['dom', 'bug80602.phpt'],
	['dom', 'bug80602_2.phpt'],
	['dom', 'bug80602_3.phpt'],
	['dom', 'bug80602_4.phpt'],
	['dom', 'bug80927.phpt'],
	['dom', 'bug81433.phpt'],
	['dom', 'bug81642.phpt'],
	['dom', 'bug_lifetime_parentNode_getAttributeNodeNS.phpt'],
	['dom', 'canonicalization.phpt'],
	['dom', 'childNodes_current_crash.phpt'],
	['dom', 'clone_nodes.phpt'],
	['dom', 'createAttributeNS_prefix_conflicts/setAttributeNS_with_prefix.phpt'],
	['dom', 'createAttributeNS_prefix_conflicts/setAttributeNS_without_prefix.phpt'],
	['dom', 'createAttributeNS_prefix_conflicts/setAttribute_mixed_prefix.phpt'],
	['dom', 'createAttributeNS_prefix_conflicts/setAttribute_with_prefix.phpt'],
	['dom', 'createAttributeNS_prefix_conflicts/setAttribute_without_prefix.phpt'],
	['dom', 'delayed_freeing/attribute_declaration.phpt'],
	['dom', 'delayed_freeing/comment_node.phpt'],
	['dom', 'delayed_freeing/direct_construction.phpt'],
	['dom', 'delayed_freeing/document_fragment.phpt'],
	['dom', 'delayed_freeing/dom_character_data.phpt'],
	['dom', 'delayed_freeing/dtd_node.phpt'],
	['dom', 'delayed_freeing/element_declaration.phpt'],
	['dom', 'delayed_freeing/element_uaf_crash.phpt'],
	['dom', 'delayed_freeing/entity_declaration.phpt'],
	['dom', 'delayed_freeing/entity_reference.phpt'],
	['dom', 'delayed_freeing/gh9628_1.phpt'],
	['dom', 'delayed_freeing/gh9628_2.phpt'],
	['dom', 'delayed_freeing/namespace_definition_crash.phpt'],
	['dom', 'delayed_freeing/namespace_definition_crash_in_attribute.phpt'],
	['dom', 'delayed_freeing/namespace_xmlns_declaration.phpt'],
	['dom', 'delayed_freeing/namespace_xmlns_declaration_attribute_variation.phpt'],
	['dom', 'delayed_freeing/notation_declaration.phpt'],
	['dom', 'delayed_freeing/processing_instruction.phpt'],
	['dom', 'delayed_freeing/text_node.phpt'],
	['dom', 'delayed_freeing/without_contructor.phpt'],
	['dom', 'dom001.phpt'],
	['dom', 'dom002.phpt'],
	['dom', 'dom003.phpt'],
	['dom', 'dom005.phpt'],
	['dom', 'dom006.phpt'],
	['dom', 'dom007.phpt'],
	['dom', 'dom_comment_basic.phpt'],
	['dom', 'dom_comment_variation.phpt'],
	['dom', 'dom_create_element.phpt'],
	['dom', 'dom_import_simplexml.phpt'],
	['dom', 'dom_set_attr_node.phpt'],
	['dom', 'domattributes.phpt'],
	['dom', 'domchardata.phpt'],
	['dom', 'domdocument_createentityreference_001.phpt'],
	['dom', 'domelement.phpt'],
	['dom', 'domobject_debug_handler.phpt'],
	['dom', 'domxpath.phpt'],
	['dom', 'element_child_and_parent_node_without_document.phpt'],
	['dom', 'entity_reference_stale_01.phpt'],
	['dom', 'entity_reference_stale_02.phpt'],
	['dom', 'fragments_multiple_nodes_DOMParentNode.phpt'],
	['dom', 'getElementsByTagName_liveness_deallocated_document.phpt'],
	['dom', 'gh10234.phpt'],
	['dom', 'gh11288.phpt'],
	['dom', 'gh11289.phpt'],
	['dom', 'gh11290.phpt'],
	['dom', 'gh11347.phpt'],
	['dom', 'gh11500.phpt'],
	['dom', 'gh11625.phpt'],
	['dom', 'gh11682.phpt'],
	['dom', 'gh11791.phpt'],
	['dom', 'gh11830/attribute_variation.phpt'],
	['dom', 'gh11830/document_variation.phpt'],
	['dom', 'gh11830/hierarchy_variation.phpt'],
	['dom', 'gh11830/type_variation.phpt'],
	['dom', 'gh11906.phpt'],
	['dom', 'gh12002.phpt'],
	['dom', 'gh12616_1.phpt'],
	['dom', 'gh12616_2.phpt'],
	['dom', 'gh12616_3.phpt'],
	['dom', 'gh12870_a.phpt'],
	['dom', 'gh12870_b.phpt'],
	['dom', 'gh13012.phpt'],
	['dom', 'gh13012_ns.phpt'],
	['dom', 'gh14343.phpt'],
	['dom', 'gh14702.phpt'],
	['dom', 'gh9142.phpt'],
	['dom', 'manually_call_constructor/attribute.phpt'],
	['dom', 'manually_call_constructor/cdatasection.phpt'],
	['dom', 'manually_call_constructor/comment.phpt'],
	['dom', 'manually_call_constructor/document.phpt'],
	['dom', 'manually_call_constructor/documentfragment.phpt'],
	['dom', 'manually_call_constructor/element.phpt'],
	['dom', 'manually_call_constructor/entityreference.phpt'],
	['dom', 'manually_call_constructor/processinginstruction.phpt'],
	['dom', 'manually_call_constructor/text.phpt'],
	['dom', 'not_serializable.phpt'],
	['dom', 'not_unserializable.phpt'],
	['dom', 'php_function_edge_cases.phpt'],
	['dom', 'property_write_errors.phpt'],
	['dom', 'reconcile_reused_namespace.phpt'],
	['dom', 'registerNodeClass_abstract_class.phpt'],
	['dom', registerNodeClassPhpt],
	['dom', 'replaceWith_non_viable_next_sibling.phpt'],
	['dom', 'setAttributeNodeNS_same_uri_different_prefix.phpt'],
	['dom', 'specific_namespace_behaviour.phpt'],
	['dom', 'toString_exceptions.phpt'],
	['dom', 'uaf_doctype_iterator.phpt'],
	['dom', 'xpath_domnamespacenode.phpt'],
	['dom', 'xpath_domnamespacenode_advanced.phpt'],
	['zlib', '001.phpt'],
	['zlib', '002.phpt'],
	['zlib', '005.phpt'],
	['sqlite3', 'sqlite3_01_open.phpt'],
	['sqlite3', 'bug45798.phpt'],
	['sqlite3', 'bug53463.phpt'],
	['tidy', '001.phpt'],
	['tidy', '006.phpt'],
	['iconv', 'bug48147.phpt'],
	['iconv', 'bug51250.phpt'],
	['iconv', 'bug53304.phpt'],
	['intl', 'badargs.phpt'],
	['intl', 'breakiter___construct.phpt'],
	['intl', 'breakiter___construct_error.phpt'],
	['intl', 'breakiter_clone_basic.phpt'],
	['intl', 'breakiter_createCodePointInstance_basic.phpt'],
	['intl', 'breakiter_current_basic.phpt'],
	['intl', 'breakiter_factories_basic.phpt'],
	['intl', 'breakiter_first_basic.phpt'],
	['intl', 'breakiter_following_basic.phpt'],
	['intl', 'breakiter_getPartsIterator_error.phpt'],
	['intl', 'breakiter_getPartsIterator_var1.phpt'],
	['intl', 'breakiter_getText_basic.phpt'],
	['intl', 'breakiter_isBoundary_basic.phpt'],
	['intl', 'breakiter_last_basic.phpt'],
	['intl', 'breakiter_next_basic.phpt'],
	['intl', 'breakiter_previous_basic.phpt'],
	['intl', 'breakiter_setText_basic.phpt'],
	['intl', 'bug12887.phpt'],
	['intl', 'bug14562.phpt'],
	['intl', 'bug48227.phpt'],
	['intl', 'bug50590.phpt'],
	['intl', 'bug55562.phpt'],
	['intl', 'bug60192-compare.phpt'],
	['intl', 'bug60192-getlocale.phpt'],
	['intl', 'bug60192-getsortkey.phpt'],
	['intl', 'bug60192-sort.phpt'],
	['intl', 'bug60192-sortwithsortkeys.phpt'],
	['intl', 'bug61860.phpt'],
	['intl', 'bug62017.phpt'],
	['intl', 'bug62081.phpt'],
	['intl', 'bug62082.phpt'],
	['intl', 'bug62083.phpt'],
	['intl', 'bug62759.phpt'],
	['intl', 'bug62915.phpt'],
	['intl', 'bug65732.phpt'],
	['intl', 'bug67397.phpt'],
	['intl', 'bug68447.phpt'],
	['intl', 'bug68471.phpt'],
	['intl', 'bug70451.phpt'],
	['intl', 'bug70452.phpt'],
	['intl', 'bug71020.phpt'],
	['intl', 'bug72061.phpt'],
	['intl', 'bug72241.phpt'],
	['intl', 'bug72533.phpt'],
	['intl', 'bug72639.phpt'],
	['intl', 'bug74063.phpt'],
	['intl', 'bug74264.phpt'],
	['intl', 'bug74298.phpt'],
	['intl', 'bug74433.phpt'],
	['intl', 'bug74484_MessageFormatter.phpt'],
	['intl', 'bug74705.phpt'],
	['intl', 'bug75090.phpt'],
	['intl', 'bug75193.phpt'],
	['intl', 'bug75317.phpt'],
	['intl', 'bug75318.phpt'],
	['intl', 'bug75378.phpt'],
	['intl', 'bug76556.phpt'],
	['intl', 'bug77895.phpt'],
	['intl', 'bug78804.phpt'],
	['intl', 'bug80763.phpt'],
	['intl', 'bug81019.phpt'],
	['intl', 'calendar_add_basic.phpt'],
	['intl', 'calendar_add_error.phpt'],
	['intl', 'calendar_before_after_error.phpt'],
	['intl', 'calendar_clear_basic.phpt'],
	['intl', 'calendar_clear_error.phpt'],
	['intl', 'calendar_const_field_field_count.phpt'],
	['intl', 'calendar_createInstance_basic.phpt'],
	['intl', 'calendar_createInstance_error.phpt'],
	['intl', 'calendar_createInstance_variation1.phpt'],
	['intl', 'calendar_equals_before_after_basic.phpt'],
	['intl', 'calendar_equals_error.phpt'],
	['intl', 'calendar_fieldDifference_basic.phpt'],
	['intl', 'calendar_fieldDifference_error.phpt'],
	['intl', 'calendar_fromDateTime_basic.phpt'],
	['intl', 'calendar_fromDateTime_error.phpt'],
	['intl', 'calendar_getAvailableLocales_basic.phpt'],
	['intl', 'calendar_getDayOfWeekType_error.phpt'],
	['intl', 'calendar_getErrorCode_error.phpt'],
	['intl', 'calendar_getErrorCode_getErrorMessage_basic.phpt'],
	['intl', 'calendar_getErrorMessage_error.phpt'],
	['intl', 'calendar_getFirstDayOfWeek_basic.phpt'],
	['intl', 'calendar_getFirstDayOfWeek_error.phpt'],
	['intl', 'calendar_getKeywordValuesForLocale_basic.phpt'],
	['intl', 'calendar_getLocale_basic.phpt'],
	['intl', 'calendar_getLocale_error.phpt'],
	['intl', 'calendar_getMinimalDaysInFirstWeek_basic.phpt'],
	['intl', 'calendar_getMinimalDaysInFirstWeek_error.phpt'],
	['intl', 'calendar_getNow_basic.phpt'],
	['intl', 'calendar_getSkipped_RepeatedWallTimeOption_error.phpt'],
	['intl', 'calendar_getTimeZone_basic.phpt'],
	['intl', 'calendar_getTimeZone_error.phpt'],
	['intl', 'calendar_getTime_basic.phpt'],
	['intl', 'calendar_getTime_error.phpt'],
	['intl', 'calendar_getType_basic.phpt'],
	['intl', 'calendar_getType_error.phpt'],
	['intl', 'calendar_getWeekendTransition_basic.phpt'],
	['intl', 'calendar_getWeekendTransition_error.phpt'],
	['intl', 'calendar_getXMaximum_basic.phpt'],
	['intl', 'calendar_getXMinimum_basic.phpt'],
	['intl', 'calendar_get_Least_Greatest_Minimum_Maximum_error.phpt'],
	['intl', 'calendar_get_basic.phpt'],
	['intl', 'calendar_get_getActualMaximum_Minumum_error.phpt'],
	['intl', 'calendar_get_getActualMaximum_Minumum_error2.phpt'],
	['intl', 'calendar_get_setRepeatedWallTimeOption_basic.phpt'],
	['intl', 'calendar_get_setSkippedWallTimeOption_basic.phpt'],
	['intl', 'calendar_inDaylightTime_basic.phpt'],
	['intl', 'calendar_inDaylightTime_error.phpt'],
	['intl', 'calendar_isEquivalentTo_basic.phpt'],
	['intl', 'calendar_isEquivalentTo_error.phpt'],
	['intl', 'calendar_isLenient_error.phpt'],
	['intl', 'calendar_isSet_basic.phpt'],
	['intl', 'calendar_isSet_empty_time.phpt'],
	['intl', 'calendar_isSet_error.phpt'],
	['intl', 'calendar_isWeekend_basic.phpt'],
	['intl', 'calendar_isWeekend_error.phpt'],
	['intl', 'calendar_is_set_lenient_basic.phpt'],
	['intl', 'calendar_roll_basic.phpt'],
	['intl', 'calendar_roll_error.phpt'],
	['intl', 'calendar_roll_variation1.phpt'],
	['intl', 'calendar_setFirstDayOfWeek_basic.phpt'],
	['intl', 'calendar_setFirstDayOfWeek_error.phpt'],
	['intl', 'calendar_setLenient_error.phpt'],
	['intl', 'calendar_setMinimalDaysInFirstWeek_basic.phpt'],
	['intl', 'calendar_setMinimalDaysInFirstWeek_error.phpt'],
	['intl', 'calendar_setSkipped_RepeatedWallTimeOption_error.phpt'],
	['intl', 'calendar_setTimeZone_basic.phpt'],
	['intl', 'calendar_setTimeZone_error.phpt'],
	['intl', 'calendar_setTimeZone_error2.phpt'],
	['intl', 'calendar_setTimeZone_variation1.phpt'],
	['intl', 'calendar_setTimeZone_variation2.phpt'],
	['intl', 'calendar_setTime_basic.phpt'],
	['intl', 'calendar_setTime_error.phpt'],
	['intl', 'calendar_set_basic.phpt'],
	['intl', 'calendar_set_date.phpt'],
	['intl', 'calendar_set_date_time.phpt'],
	['intl', 'calendar_set_error.phpt'],
	['intl', 'calendar_set_variation1.phpt'],
	['intl', 'calendar_toDateTime_basic.phpt'],
	['intl', 'calendar_toDateTime_error.phpt'],
	['intl', 'collation_customization.phpt'],
	['intl', 'collator_get_error_code.phpt'],
	['intl', 'collator_get_error_message.phpt'],
	['intl', 'collator_get_set_attribute.phpt'],
	['intl', 'collator_get_set_strength.phpt'],
	['intl', 'cpbi_clone_equality.phpt'],
	['intl', 'cpbi_getLastCodePoint_basic.phpt'],
	['intl', 'cpbi_parts_iterator.phpt'],
	['intl', 'dateformat___construct_bad_tz_cal.phpt'],
	['intl', 'dateformat_bug65683.phpt'],
	['intl', 'dateformat_bug65683_2.phpt'],
	['intl', 'dateformat_bug68893.phpt'],
	['intl', 'dateformat_bug71516.phpt'],
	['intl', 'dateformat_clone2.phpt'],
	['intl', 'dateformat_clone_bad_obj.phpt'],
	['intl', 'dateformat_formatObject_error.phpt'],
	['intl', 'dateformat_format_relative.phpt'],
	['intl', 'dateformat_get_datetype.phpt'],
	['intl', 'dateformat_get_set_pattern2.phpt'],
	['intl', 'dateformat_get_timetype.phpt'],
	['intl', 'dateformat_get_timezone_id.phpt'],
	['intl', 'dateformat_invalid_timezone.phpt'],
	['intl', 'dateformat_is_set_lenient.phpt'],
	['intl', 'dateformat_setTimeZone_error.phpt'],
	['intl', 'datepatterngenerator_clone.phpt'],
	['intl', 'datepatterngenerator_error.phpt'],
	['intl', 'deprecated_number_formater_type_currency.phpt'],
	['intl', 'formatter_clone.phpt'],
	['intl', 'formatter_clone_bad_obj.phpt'],
	['intl', 'formatter_fail.phpt'],
	['intl', 'formatter_format_and_parse_errors.phpt'],
	['intl', 'formatter_format_conv.phpt'],
	['intl', 'formatter_format_currency2.phpt'],
	['intl', 'formatter_get_error.phpt'],
	['intl', 'formatter_parse.phpt'],
	['intl', 'formatter_parse_currency.phpt'],
	['intl', 'gh10647.phpt'],
	['intl', 'gh11658.phpt'],
	['intl', 'gh12020.phpt'],
	['intl', 'gh12243.phpt'],
	['intl', 'gh12282.phpt'],
	['intl', 'gh12943.phpt'],
	['intl', 'gh7734.phpt'],
	['intl', 'gh8115.phpt'],
	['intl', 'gh8364.phpt'],
	['intl', 'grapheme_empty.phpt'],
	['intl', 'grapheme_out_of_bounds.phpt'],
	['intl', 'gregoriancalendar___construct_basic.phpt'],
	['intl', 'gregoriancalendar___construct_error.phpt'],
	['intl', 'gregoriancalendar___construct_variant1.phpt'],
	['intl', 'gregoriancalendar_getGregorianChange_error.phpt'],
	['intl', 'gregoriancalendar_get_setGregorianChange_basic.phpt'],
	['intl', 'gregoriancalendar_isLeapYear_basic.phpt'],
	['intl', 'gregoriancalendar_isLeapYear_error.phpt'],
	['intl', 'idn.phpt'],
	['intl', 'idn_bug76829.phpt'],
	['intl', 'ini_use_exceptions_basic.phpt'],
	['intl', 'intl_error_name.phpt'],
	['intl', 'intl_get_error_code.phpt'],
	['intl', 'intl_get_error_message.phpt'],
	['intl', 'intl_icu_data_version_constant.phpt'],
	['intl', 'intl_icu_version_constant.phpt'],
	['intl', 'intl_is_failure.phpt'],
	['intl', 'locale/bug72809.phpt'],
	['intl', 'locale/bug74993.phpt'],
	['intl', 'locale_accept.phpt'],
	['intl', 'locale_bug66289.phpt'],
	['intl', 'locale_bug72658.phpt'],
	['intl', 'locale_bug74439.phpt'],
	['intl', 'locale_compose_locale.phpt'],
	['intl', 'locale_get_all_variants.phpt'],
	['intl', 'locale_get_default.phpt'],
	['intl', 'locale_get_display_language3.phpt'],
	['intl', 'locale_get_display_variant2.phpt'],
	['intl', 'locale_get_keywords2.phpt'],
	['intl', 'locale_get_primary_language.phpt'],
	['intl', 'locale_get_region.phpt'],
	['intl', 'locale_get_script.phpt'],
	['intl', 'locale_parse_locale2.phpt'],
	['intl', 'locale_set_default.phpt'],
	['intl', 'msgfmt_bug70484.phpt'],
	['intl', 'msgfmt_clone.phpt'],
	['intl', 'msgfmt_clone_bad_obj.phpt'],
	['intl', 'msgfmt_fail2.phpt'],
	['intl', 'msgfmt_format.phpt'],
	['intl', 'msgfmt_format_error1.phpt'],
	['intl', 'msgfmt_format_error2.phpt'],
	['intl', 'msgfmt_format_error3.phpt'],
	['intl', 'msgfmt_format_error4.phpt'],
	['intl', 'msgfmt_format_error5.phpt'],
	['intl', 'msgfmt_format_error6.phpt'],
	['intl', 'msgfmt_format_mixed_params.phpt'],
	['intl', 'msgfmt_format_subpatterns.phpt'],
	['intl', 'msgfmt_format_subpatterns_named.phpt'],
	['intl', 'msgfmt_get_locale.phpt'],
	['intl', 'msgfmt_get_set_pattern.phpt'],
	['intl', 'msgfmt_millisecond_dates.phpt'],
	['intl', 'msgfmt_parse.phpt'],
	['intl', 'msgfmt_setPattern_cache.phpt'],
	['intl', 'normalizer_normalize.phpt'],
	['intl', 'rbbiter___construct_basic.phpt'],
	['intl', 'rbbiter_getRuleStatusVec_basic.phpt'],
	['intl', 'rbbiter_getRuleStatus_basic.phpt'],
	['intl', 'regression_sort_and_cow.phpt'],
	['intl', 'regression_sort_eq.phpt'],
	['intl', 'regression_sortwsk_and_cow.phpt'],
	['intl', 'regression_sortwsk_eq.phpt'],
	['intl', 'resourcebundle_arrayaccess.phpt'],
	['intl', 'resourcebundle_countable.phpt'],
	['intl', 'resourcebundle_create.phpt'],
	['intl', 'resourcebundle_double_ctor.phpt'],
	['intl', 'resourcebundle_individual.phpt'],
	['intl', 'resourcebundle_iterator.phpt'],
	['intl', 'resourcebundle_locales.phpt'],
	['intl', 'resourcebundle_traversable.phpt'],
	['intl', 'spoofchecker_self_references.phpt'],
	['intl', 'spoofchecker_typed_references.phpt'],
	['intl', 'timezone_clone_basic.phpt'],
	['intl', 'timezone_clone_error.phpt'],
	['intl', 'timezone_countEquivalentIDs_basic.phpt'],
	['intl', 'timezone_countEquivalentIDs_error.phpt'],
	['intl', 'timezone_createDefault_basic.phpt'],
	['intl', 'timezone_createEnumeration_basic.phpt'],
	['intl', 'timezone_createEnumeration_error.phpt'],
	['intl', 'timezone_createEnumeration_variation1.phpt'],
	['intl', 'timezone_createEnumeration_variation2.phpt'],
	['intl', 'timezone_createTimeZoneIDEnumeration_basic.phpt'],
	['intl', 'timezone_createTimeZoneIDEnumeration_error.phpt'],
	['intl', 'timezone_createTimeZoneIDEnumeration_variant1.phpt'],
	['intl', 'timezone_createTimeZoneIDEnumeration_variant2.phpt'],
	['intl', 'timezone_createTimeZone_basic.phpt'],
	['intl', 'timezone_createTimeZone_error.phpt'],
	['intl', 'timezone_equals_basic.phpt'],
	['intl', 'timezone_equals_error.phpt'],
	['intl', 'timezone_fromDateTimeZone_basic.phpt'],
	['intl', 'timezone_fromDateTimeZone_error.phpt'],
	['intl', 'timezone_getCanonicalID_basic.phpt'],
	['intl', 'timezone_getCanonicalID_error.phpt'],
	['intl', 'timezone_getDSTSavings_basic.phpt'],
	['intl', 'timezone_getDSTSavings_error.phpt'],
	['intl', 'timezone_getDisplayName_basic.phpt'],
	['intl', 'timezone_getDisplayName_error.phpt'],
	['intl', 'timezone_getDisplayName_variant1.phpt'],
	['intl', 'timezone_getEquivalentID_basic.phpt'],
	['intl', 'timezone_getEquivalentID_error.phpt'],
	['intl', 'timezone_getErrorCode_error.phpt'],
	['intl', 'timezone_getErrorMessage_error.phpt'],
	['intl', 'timezone_getGMT_basic.phpt'],
	['intl', 'timezone_getID_error.phpt'],
	['intl', 'timezone_getOffset_basic.phpt'],
	['intl', 'timezone_getRawOffset_basic.phpt'],
	['intl', 'timezone_getRawOffset_error.phpt'],
	['intl', 'timezone_getRegion_basic.phpt'],
	['intl', 'timezone_getRegion_error.phpt'],
	['intl', 'timezone_getTZData_basic.phpt'],
	['intl', 'timezone_getUnknown_basic.phpt'],
	['intl', 'timezone_hasSameRules_basic.phpt'],
	['intl', 'timezone_hasSameRules_error.phpt'],
	['intl', 'timezone_toDateTimeZone_basic.phpt'],
	['intl', 'timezone_toDateTimeZone_error.phpt'],
	['intl', 'timezone_useDaylightTime_basic.phpt'],
	['intl', 'timezone_useDaylightTime_error.phpt'],
	['intl', 'transliterator_child.phpt'],
	['intl', 'transliterator_clone.phpt'],
	['intl', 'transliterator_create_basic.phpt'],
	['intl', 'transliterator_create_error.phpt'],
	['intl', 'transliterator_create_from_rule_basic.phpt'],
	['intl', 'transliterator_create_from_rule_error.phpt'],
	['intl', 'transliterator_create_inverse_basic.phpt'],
	['intl', 'transliterator_create_inverse_error.phpt'],
	['intl', 'transliterator_get_error_code_basic.phpt'],
	['intl', 'transliterator_get_error_code_error.phpt'],
	['intl', 'transliterator_get_error_message_basic.phpt'],
	['intl', 'transliterator_get_error_message_error.phpt'],
	['intl', 'transliterator_list_ids_basic.phpt'],
	['intl', 'transliterator_property_id.phpt'],
	['intl', 'transliterator_transliterate_basic.phpt'],
	['intl', 'transliterator_transliterate_error.phpt'],
	['intl', 'transliterator_transliterate_variant1.phpt'],
	['intl', 'uconverter___construct_error.phpt'],
	['intl', 'uconverter_bug66873.phpt'],
	['intl', 'uconverter_enum.phpt'],
	['intl', 'uconverter_func_basic.phpt'],
	['intl', 'uconverter_func_subst.phpt'],
	['intl', 'uconverter_getDestinationEncoding.phpt'],
	['intl', 'uconverter_getSourceEncoding.phpt'],
	['intl', 'uconverter_getstandards_basic.phpt'],
	['intl', 'uconverter_oop_algo.phpt'],
	['intl', 'uconverter_oop_basic.phpt'],
	['intl', 'uconverter_oop_callback_return.phpt'],
	['intl', 'uconverter_oop_subst.phpt'],
	['intl', 'uconverter_setSourceEncoding.phpt'],
	['xmlwriter', '001.phpt'],
	['xmlwriter', '002.phpt'],
	['xmlwriter', '003.phpt'],
	['xmlwriter', '004.phpt'],
	['xmlwriter', '005-mb.phpt'],
	['xmlwriter', '005.phpt'],
	['xmlwriter', '006.phpt'],
	['xmlwriter', '007.phpt'],
	['xmlwriter', '008.phpt'],
	['xmlwriter', '009.phpt'],
	['xmlwriter', '010.phpt'],
	['xmlwriter', '011.phpt'],
	['xmlwriter', '012.phpt'],
	['xmlwriter', 'bug39504.phpt'],
	['xmlwriter', 'bug41287.phpt'],
	['xmlwriter', 'bug41326.phpt'],
	['xmlwriter', 'bug48204.phpt'],
	['xmlwriter', 'bug71536.phpt'],
	['xmlwriter', 'bug79344.phpt'],
	['xmlwriter', 'OO_001.phpt'],
	['xmlwriter', 'OO_002.phpt'],
	['xmlwriter', 'OO_003.phpt'],
	['xmlwriter', 'OO_004.phpt'],
	['xmlwriter', 'OO_005.phpt'],
	['xmlwriter', 'OO_006.phpt'],
	['xmlwriter', 'OO_007.phpt'],
	['xmlwriter', 'OO_008.phpt'],
	['xmlwriter', 'OO_009.phpt'],
	['xmlwriter', 'OO_010.phpt'],
	['xmlwriter', 'OO_011.phpt'],
	['xmlwriter', 'OO_012.phpt'],
	['xmlwriter', 'OO_013.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_001.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_003.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_004.phpt'],
	['xmlwriter', 'xmlwriter_open_uri_error_005.phpt'],
	['xmlwriter', 'xmlwriter_write_attribute_ns_basic_001.phpt'],
	['xmlwriter', 'xmlwriter_write_dtd_basic_001.phpt'],
	['xmlreader', '001.phpt'],
	['xmlreader', '002.phpt'],
	['xmlreader', '003.phpt'],
	['xmlreader', '004.phpt'],
	['xmlreader', 'open_error.phpt'],
	['xmlreader', 'readString_basic.phpt'],
	['zlib', '003.phpt'],
	['zlib', '006.phpt'],
	...(atLeast(8, 5) ? [] : removedZlibPhptsInPhp85.slice(0, 3)),
	['zlib', '008.phpt'],
	['zlib', 'bug48725.phpt'],
	['zlib', 'bug48725_2.phpt'],
	['zlib', 'bug61287.phpt'],
	['zlib', 'bug61443.phpt'],
	['zlib', 'bug61820.phpt'],
	['zlib', 'bug71417.phpt'],
	['zlib', 'bug73944.phpt'],
	['zlib', 'bug74240.phpt'],
	['zlib', 'bug75273.phpt'],
	['zlib', 'bug75299.phpt'],
	['zlib', 'bug_34821.phpt'],
	['zlib', 'bug_52944.phpt'],
	['zlib', 'deflate_add_basic.phpt'],
	['zlib', 'deflate_add_buffer_full.phpt'],
	['zlib', 'deflate_add_error.phpt'],
	['zlib', 'deflate_init_error.phpt'],
	['zlib', 'deflate_init_reuse.phpt'],
	['zlib', 'dictionary_usage.phpt'],
	['zlib', 'gzclose_basic.phpt'],
	['zlib', 'gzcompress_error1.phpt'],
	['zlib', 'gzcompress_variation1.phpt'],
	['zlib', 'gzdeflate_error1.phpt'],
	['zlib', 'gzdeflate_variation1.phpt'],
	['zlib', 'gzencode_error1.phpt'],
	['zlib', 'gzeof_basic.phpt'],
	['zlib', 'gzeof_variation1.phpt'],
	['zlib', 'gzfile_basic.phpt'],
	['zlib', 'gzfile_basic2.phpt'],
	['zlib', 'gzfile_variation15.phpt'],
	['zlib', 'gzfile_variation7.phpt'],
	...(atLeast(8, 5) ? [] : removedZlibPhptsInPhp85.slice(3, 7)),
	['zlib', 'gzfilegzreadfile.phpt'],
	['zlib', 'gzgets_basic.phpt'],
	['zlib', 'gzinflate-bug42663.phpt'],
	['zlib', 'gzinflate_error1.phpt'],
	['zlib', 'gzinflate_length.phpt'],
	['zlib', 'gzopen_basic.phpt'],
	['zlib', 'gzopen_basic2.phpt'],
	['zlib', 'gzopen_variation4.phpt'],
	['zlib', 'gzopen_variation5.phpt'],
	['zlib', 'gzopen_variation6.phpt'],
	['zlib', 'gzopen_variation7.phpt'],
	['zlib', 'gzopen_variation8.phpt'],
	['zlib', 'gzopen_variation9.phpt'],
	['zlib', 'gzpassthru_basic.phpt'],
	['zlib', 'gzputs_basic.phpt'],
	['zlib', 'gzread_basic.phpt'],
	['zlib', 'gzread_error2.phpt'],
	['zlib', 'gzread_variation1.phpt'],
	['zlib', 'gzreadgzwrite.phpt'],
	['zlib', 'gzreadgzwriteplain.phpt'],
	['zlib', 'gzrewind_basic.phpt'],
	['zlib', 'gzrewind_basic2.phpt'],
	['zlib', 'gzrewind_variation1.phpt'],
	['zlib', 'gzseek_basic.phpt'],
	['zlib', 'gzseek_basic2.phpt'],
	['zlib', 'gzseek_variation1.phpt'],
	['zlib', 'gzseek_variation2.phpt'],
	['zlib', 'gzseek_variation3.phpt'],
	['zlib', 'gzseek_variation4.phpt'],
	['zlib', 'gzseek_variation5.phpt'],
	['zlib', 'gzseek_variation6.phpt'],
	['zlib', 'gzseek_variation7.phpt'],
	['zlib', 'gztell_basic.phpt'],
	['zlib', 'gztell_basic2.phpt'],
	['zlib', 'gzuncompress_basic1.phpt'],
	['zlib', 'gzuncompress_error1.phpt'],
	['zlib', 'gzwrite_basic.phpt'],
	['zlib', 'gzwrite_error2.phpt'],
	['zlib', 'gzwrite_variation1.phpt'],
	['zlib', 'inflate_add_error.phpt'],
	['zlib', 'inflate_get_read_len.phpt'],
	['zlib', 'inflate_get_status.phpt'],
	['zlib', 'inflate_init_error.phpt'],
	['zlib', 'inflate_init_reuse.phpt'],
	['zlib', 'ob_002.phpt'],
	['zlib', 'readgzfile_basic.phpt'],
	['zlib', 'readgzfile_basic2.phpt'],
	['zlib', 'readgzfile_variation15.phpt'],
	['zlib', 'readgzfile_variation7.phpt'],
	...(atLeast(8, 5) ? [] : removedZlibPhptsInPhp85.slice(7)),
	['zlib', 'zlib_filter_deflate.phpt'],
	['zlib', 'zlib_filter_deflate2.phpt'],
	['zlib', 'zlib_filter_inflate.phpt'],
	['zlib', 'zlib_get_coding_type_basic.phpt'],
	['zlib', 'zlib_get_coding_type_br.phpt'],
	['zlib', 'zlib_scheme_copy_basic.phpt'],
	['zlib', 'zlib_scheme_copy_variation1.phpt'],
	['zlib', 'zlib_scheme_copy_variation2.phpt'],
	['zlib', 'zlib_scheme_dir_basic.phpt'],
	['zlib', 'zlib_scheme_file_basic.phpt'],
	['zlib', 'zlib_scheme_file_get_contents_basic.phpt'],
	['zlib', 'zlib_scheme_file_put_contents_basic.phpt'],
	['zlib', 'zlib_scheme_file_read_file_basic.phpt'],
	['zlib', 'zlib_scheme_fopen_basic.phpt'],
	['zlib', 'zlib_scheme_fopen_variation1.phpt'],
	['zlib', 'zlib_scheme_rename_basic.phpt'],
	['zlib', 'zlib_scheme_stat_basic.phpt'],
	['zlib', 'zlib_scheme_stat_basic2.phpt'],
	['zlib', 'zlib_scheme_unlink_basic.phpt'],
	['zlib', 'zlib_wrapper_fflush_basic.phpt'],
	['zlib', 'zlib_wrapper_flock_basic.phpt'],
	['zlib', 'zlib_wrapper_fstat_basic.phpt'],
	['zlib', 'zlib_wrapper_ftruncate_basic.phpt'],
	['zlib', 'zlib_wrapper_meta_data_basic.phpt'],
	['sqlite3', 'bug47159.phpt'],
	['sqlite3', 'bug66550.phpt'],
	['sqlite3', 'bug68760.phpt'],
	['sqlite3', 'bug69972.phpt'],
	['sqlite3', 'bug70628.phpt'],
	['sqlite3', 'bug71049.phpt'],
	['sqlite3', 'bug72571.phpt'],
	['sqlite3', 'bug72668.phpt'],
	['sqlite3', 'bug73333.phpt'],
	['sqlite3', 'bug76665.phpt'],
	['sqlite3', 'bug77051.phpt'],
	['sqlite3', 'bug79294.phpt'],
	['sqlite3', 'exception_from_toString.phpt'],
	['sqlite3', 'gh11451.phpt'],
	['sqlite3', 'gh11878.phpt'],
	['sqlite3', 'sqlite3_01_open-mb.phpt'],
	['sqlite3', 'sqlite3_02_create.phpt'],
	['sqlite3', 'sqlite3_02_open.phpt'],
	['sqlite3', 'sqlite3_03_insert.phpt'],
	['sqlite3', 'sqlite3_04_update.phpt'],
	['sqlite3', 'sqlite3_05_delete.phpt'],
	['sqlite3', 'sqlite3_06_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_07_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_08_udf.phpt'],
	['sqlite3', 'sqlite3_09_blob_bound_param.phpt'],
	['sqlite3', 'sqlite3_10_bound_value_name.phpt'],
	['sqlite3', 'sqlite3_12_unfinalized_stmt_cleanup.phpt'],
	['sqlite3', 'sqlite3_13_skip_all_cleanup.phpt'],
	['sqlite3', 'sqlite3_14_querysingle.phpt'],
	['sqlite3', 'sqlite3_16_select_no_results.phpt'],
	['sqlite3', 'sqlite3_17_version.phpt'],
	['sqlite3', 'sqlite3_18_changes.phpt'],
	['sqlite3', 'sqlite3_19_columninfo.phpt'],
	['sqlite3', 'sqlite3_20_error.phpt'],
	['sqlite3', 'sqlite3_23_escape_string.phpt'],
	['sqlite3', 'sqlite3_24_last_insert_rowid.phpt'],
	['sqlite3', 'sqlite3_25_create_aggregate.phpt'],
	['sqlite3', 'sqlite3_26_reset_prepared_stmt.phpt'],
	['sqlite3', 'sqlite3_27_reset_prepared_stmt_result.phpt'],
	['sqlite3', 'sqlite3_28_clear_bindings.phpt'],
	['sqlite3', 'sqlite3_29_createfunction.phpt'],
	['sqlite3', 'sqlite3_30_blobopen.phpt'],
	['sqlite3', 'sqlite3_31_changes.phpt'],
	['sqlite3', 'sqlite3_33_createAggregate_notcallable.phpt'],
	['sqlite3', 'sqlite3_33_reset.phpt'],
	['sqlite3', 'sqlite3_36_create_collation.phpt'],
	['sqlite3', 'sqlite3_38_backup.phpt'],
	['sqlite3', 'sqlite3_38_extended_error.phpt'],
	['sqlite3', 'sqlite3_39_toggleExtended.phpt'],
	['sqlite3', 'sqlite3_40_setauthorizer.phpt'],
	['sqlite3', 'sqlite3_bind_bug68849.phpt'],
	['sqlite3', 'sqlite3_blob_bind_resource.phpt'],
	['sqlite3', 'sqlite3_bound_value_at_name.phpt'],
	['sqlite3', 'sqlite3_busyTimeout.phpt'],
	['sqlite3', 'sqlite3_enable_exceptions.phpt'],
	['sqlite3', 'sqlite3_open_empty_string.phpt'],
	['sqlite3', 'sqlite3_prepare_001.phpt'],
	['sqlite3', 'sqlite3_prepare_faultystmt.phpt'],
	['sqlite3', 'sqlite3_prepare_with_empty_string.phpt'],
	['sqlite3', 'sqlite3_trampoline_create_aggregate.phpt'],
	['sqlite3', 'sqlite3_trampoline_create_collation.phpt'],
	['sqlite3', 'sqlite3_trampoline_createfunction.phpt'],
	['sqlite3', 'sqlite3_trampoline_setauthorizer.phpt'],
	['sqlite3', 'sqlite3stmt_getsql.phpt'],
	['sqlite3', 'sqlite3stmt_paramCount_basic.phpt'],
	['tidy', '002.phpt'],
	['tidy', '005-mb.phpt'],
	['tidy', '005.phpt'],
	['tidy', '007.phpt'],
	['tidy', '008.phpt'],
	['tidy', '009.phpt'],
	['tidy', '010.phpt'],
	['tidy', '011.phpt'],
	['tidy', '012.phpt'],
	['tidy', '013.phpt'],
	['tidy', '014.phpt'],
	['tidy', '015.phpt'],
	['tidy', '016.phpt'],
	['tidy', '018.phpt'],
	['tidy', '019.phpt'],
	['tidy', '023.phpt'],
	['tidy', '024.phpt'],
	['tidy', '025.phpt'],
	['tidy', '027.phpt'],
	['tidy', '028.phpt'],
	['tidy', '029.phpt'],
	['tidy', '030.phpt'],
	['tidy', '031.phpt'],
	['tidy', '032.phpt'],
	['tidy', '033.phpt'],
	['tidy', '034.phpt'],
	['tidy', '035.phpt'],
	['tidy', '036.phpt'],
	['tidy', 'bug54682.phpt'],
	['tidy', 'bug77040.phpt'],
	['tidy', 'bug77594.phpt'],
	['tidy', 'bug_50558.phpt'],
	['tidy', 'gh12980.phpt'],
	['tidy', 'parsing_inexistent_file.phpt'],
	['tidy', 'tidy_error.phpt'],
	['tidy', 'tidy_error1.phpt'],
	['tidy', 'uninitialized.phpt'],
	['iconv', 'bug48289.phpt'],
	['iconv', 'bug52211.phpt'],
	['iconv', 'bug52941.phpt'],
	['iconv', 'bug53891.phpt'],
	['iconv', 'bug55146.phpt'],
	['iconv', 'bug60494.phpt'],
	['iconv', 'bug63839.phpt'],
	['iconv', 'bug66828.phpt'],
	['iconv', 'bug68180.phpt'],
	['iconv', 'bug69840.phpt'],
	['iconv', 'bug72320.phpt'],
	['iconv', 'bug74230.phpt'],
	['iconv', 'bug76249.phpt'],
	['iconv', 'bug77147.phpt'],
	['iconv', 'bug78069.phpt'],
	['iconv', 'bug79200.phpt'],
	['iconv', 'gh7980.phpt'],
	['iconv', 'iconv-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv003.phpt'],
	['iconv', 'iconv_basic.phpt'],
	['iconv', 'iconv_default_charset.phpt'],
	['iconv', 'iconv_encoding_basic.phpt'],
	['iconv', 'iconv_get_encoding_basic.phpt'],
	['iconv', 'iconv_ini_encoding.phpt'],
	['iconv', 'iconv_mime_decode-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_mime_decode.phpt'],
	['iconv', 'iconv_mime_decode_headers-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_mime_decode_headers.phpt'],
	['iconv', 'iconv_mime_encode_001.phpt'],
	['iconv', 'iconv_set_encoding-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_stream_filter.phpt'],
	['iconv', 'iconv_stream_filter_delimiter.phpt'],
	['iconv', 'iconv_strlen-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strlen_basic.phpt'],
	['iconv', 'iconv_strlen_error2.phpt'],
	['iconv', 'iconv_strpos-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strpos_basic.phpt'],
	['iconv', 'iconv_strpos_error2.phpt'],
	['iconv', 'iconv_strpos_error_001.phpt'],
	['iconv', 'iconv_strpos_variation5.phpt'],
	['iconv', 'iconv_strrpos-charset-length-cve-2007-4840.phpt'],
	['iconv', 'iconv_strrpos_basic.phpt'],
	['iconv', 'iconv_strrpos_error2.phpt'],
	['iconv', 'iconv_substr-charset-length-cve-2007-4783.phpt'],
	['iconv', 'iconv_substr_basic.phpt'],
	['iconv', 'iconv_substr_error2.phpt'],
	['iconv', 'iconv_substr_out_of_bounds.phpt'],
	['iconv', 'ob_iconv_handler-charset-length-cve-2007-4840.phpt']
];

const attachOutput = php => {
	let stdOut = '';
	let stdErr = '';

	php.addEventListener('output', event => event.detail.forEach(line => void (stdOut += line)));
	php.addEventListener('error', event => event.detail.forEach(line => void (stdErr += line)));

	return {
		stdOut: () => stdOut
		, stdErr: () => stdErr
	};
};

test('runs a CLI script in Node', async () => {
	const php = new PhpCliNode(nodeRuntimeOptions({
		runtime: 'cli',
		code: 'echo "Hello, World!";'
		, version
	}));
	const {stdOut, stdErr} = attachOutput(php);

	await php.binary;

	const exitCode = await php.run();

	assert.equal(exitCode, 0);
	assert.equal(stdOut(), 'Hello, World!');
	assert.equal(stdErr(), '');
});

test(`loads the requested CLI runtime version (${version})`, async () => {
	const php = new PhpCliNode(nodeRuntimeOptions({
		runtime: 'cli',
		code: 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;'
		, version
	}));
	const {stdOut, stdErr} = attachOutput(php);

	await php.binary;

	const exitCode = await php.run();

	assert.equal(exitCode, 0);
	assert.equal(stdOut(), version);
	assert.equal(stdErr(), '');
});

for(const phptName of directCliPhpts)
{
	const phptFile = phpt(phptName);
	const runner = fs.existsSync(phptFile) ? test : test.skip;

	runner(`runs core PHPT ${phptName} directly in CLI Node (${version})`, async () => {
		await runCliPhpt({
			phptFile,
			version
		});
	});
}

for(const [extensionName, phptName] of directCliExtensionPhpts)
{
	const phptFile = extPhpt(extensionName, phptName);
	const runner = fs.existsSync(phptFile) ? test : test.skip;

	runner(`runs ${extensionName} PHPT ${phptName} directly in CLI Node (${version})`, async () => {
		await runCliPhpt({
			phptFile,
			version
		});
	});
}
