import { downloadHeaders, serveNightlyAsset } from './r2.mjs';

export const OUTPUT_LIMIT = 256 * 1024;
export const WALL_TIMEOUT_MS = 10_000;

const query = `$pdo = new PDO('cfd1:mainDb', null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$query = $pdo->prepare('SELECT ? AS answer');
$query->bindValue(1, 42, PDO::PARAM_INT);
$query->execute();
$row = $query->fetch(PDO::FETCH_ASSOC);
if ($row !== ['answer' => 42]) throw new RuntimeException('Unexpected D1 answer');
echo json_encode(['phpFullVersion' => PHP_VERSION, 'sapi' => PHP_SAPI,
 'driver' => in_array('cfd1', PDO::getAvailableDrivers(), true) ? 'cfd1' : null, 'd1' => $row], JSON_THROW_ON_ERROR);`;

const programs = Object.freeze({
	'/php/': `echo '<!doctype html><html lang="en"><meta charset="utf-8"><title>PHP on Cloudflare</title><h1>PHP on Cloudflare</h1>';
echo '<p>This page is generated by PHP ', htmlspecialchars(PHP_VERSION, ENT_QUOTES, 'UTF-8'), ' using the embedded SAPI.</p>';
echo '<nav><a href="/php/phpinfo">PHP information</a> · <a href="/php/d1">D1 prepared query</a> · <a href="/php/health">Build health</a></nav>';
echo '<p><a href="' . htmlspecialchars(vrzno_shared('artifactPath'), ENT_QUOTES, 'UTF-8') . '">Download this build</a></p></html>';`
	, '/php/phpinfo': 'phpinfo(INFO_GENERAL | INFO_CONFIGURATION | INFO_MODULES | INFO_LICENSE);'
	, '/php/d1': query
	, '/php/health': query
});

/** Create one isolate-local admission gate, never a global PHP instance or D1 handle. */
export function createPagesWorker(PhpCloudflare, build, {wallTimeoutMs = WALL_TIMEOUT_MS} = {})
{
	let busy = false;
	return {
		async fetch(request, env, context)
		{
			const pathname = new URL(request.url).pathname;
			if(pathname !== '/php' && !pathname.startsWith('/php/')) return serveNightlyAsset(request, env);
			const headers = downloadHeaders({'Cache-Control': 'no-store', 'Content-Type': 'application/json; charset=utf-8'});
			const respond = (value, status = 200) => new Response(request.method === 'HEAD' ? null : JSON.stringify(value), {status, headers});
			if(request.method === 'OPTIONS') return new Response(null, {status: 204, headers});
			if(!['GET', 'HEAD'].includes(request.method))
			{
				headers.set('Allow', 'GET, HEAD, OPTIONS');
				return respond({ok: false, error: 'method_not_allowed'}, 405);
			}
			if(pathname === '/php')
			{
				headers.set('Location', '/php/');
				return new Response(null, {status: 308, headers});
			}
			if(!Object.hasOwn(programs, pathname)) return respond({ok: false, error: 'not_found'}, 404);
			if(busy)
			{
				headers.set('Retry-After', '1');
				return respond({ok: false, error: 'php_busy'}, 503);
			}
			busy = true;
			// Cap bytes before newline-based buffering. Overflow never throws through
			// Asyncify and never releases admission before execution really settles.
			const output = new Uint8Array(OUTPUT_LIMIT);
			let length = 0, total = 0, stderr = false, overflow = false;
			const capture = (byte, error) => {
				if(byte === null || byte === undefined) return;
				if(++total > OUTPUT_LIMIT) { overflow = true; return; }
				if(error) { stderr = true; return; }
				output[length++] = byte;
			};
			const operation = (async () => {
				try
				{
					const php = new PhpCloudflare({
						cfd1: {mainDb: env.NIGHTLY_PHP_DB}
						, shared: {artifactPath: `/${build.buildId}/php-cloud-wasm/`}
						, stdout: byte => capture(byte, false)
						, stderr: byte => capture(byte, true)
					});
					const exit = await php.run(`<?php ${programs[pathname]}`);
					if(overflow) return respond({ok: false, error: 'php_output_limit'}, 502);
					if(exit !== 0 || stderr) return respond({ok: false, error: 'php_execution_failed'}, 502);
					const text = new TextDecoder().decode(output.subarray(0, length));
					if(pathname === '/php/d1' || pathname === '/php/health')
					{
						const result = JSON.parse(text);
						if(result.sapi !== 'embed' || result.driver !== 'cfd1' || result.d1?.answer !== 42
							|| !result.phpFullVersion?.startsWith(`${build.phpVersion}.`)) throw new Error('Invalid PHP health');
						return respond({ok: true, buildId: build.buildId, phpVersion: build.phpVersion, ...result});
					}
					headers.set('Content-Type', 'text/html; charset=utf-8');
					headers.set('Content-Security-Policy', "default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'");
					return new Response(request.method === 'HEAD' ? null : text, {headers});
				}
				catch { return respond({ok: false, error: 'php_execution_failed'}, 502); }
				finally { busy = false; }
			})();
			// A timeout is not cancellation. Keep admission closed until the original
			// operation settles, retaining it after the response with waitUntil.
			context?.waitUntil(operation.then(() => undefined));
			let timer;
			try
			{
				return await Promise.race([operation, new Promise(resolve => {
					timer = setTimeout(() => resolve(respond({ok: false, error: 'php_timeout'}, 504)), wallTimeoutMs);
				})]);
			}
			finally { clearTimeout(timer); }
		}
	};
}
