// Generated by bin/generate-runtime-types.mjs.
import type { PhpRuntimeArgs, PhpRuntimeValue } from './PhpBase.d.cts';
import type { PhpBase } from './PhpBase.d.cts';

export class PhpDbgWeb extends PhpBase<[], void> {
	running: boolean;
	paused: boolean;
	currentFilePtr: number | null;
	currentLinePtr: number | null;
	bpCountPtr: number | null;
	constructor(args?: PhpRuntimeArgs);
	startTransaction(): Promise<void>;
	commitTransaction(readOnly?: boolean): Promise<void>;
	run(): Promise<number>;
	provideInput(line: string): Promise<void>;
	getPrompt(): Promise<string>;
	isExecuting(): Promise<number>;
	isRunning(): Promise<number>;
	currentFile(): Promise<string>;
	currentLine(): Promise<number>;
	bpCount(): Promise<number>;
	dumpSymbols(ptr: number, php: import('./public.d.ts').PhpBinaryRuntime): object;
	dumpVars(): Promise<object | undefined>;
	dumpGlobals(): Promise<object | undefined>;
	dumpConstants(): Promise<object | undefined>;
	dumpFunctions(): Promise<object>;
	dumpClasses(): Promise<object>;
	dumpFiles(): Promise<string[]>;
	dumpBacktrace(): Promise<Array<{filename: string, lineNo: number, frame: number}>>;
	switchFrame(frame: number): Promise<number>;
	refresh(): Promise<void>;
	_enqueue(callback: (...params: Array<string | number | boolean | object | undefined>) => Promise<PhpRuntimeValue>, params?: Array<string | number | boolean | object | undefined>, readOnly?: boolean): Promise<PhpRuntimeValue>;
}
