#!/usr/bin/env make

ifdef PHP_BUILDER_DIR
PHP_DBG_DIST_DIR:=${PHP_BUILDER_DIR}/${PHP_DBG_DIST_DIR}
PHP_DBG_ASSET_DIR:=${PHP_BUILDER_DIR}/${PHP_DBG_ASSET_DIR}
endif
PHP_DBG_DIST_DIR?=${ENV_DIR}/packages/php-dbg-wasm
PHP_DBG_ASSET_DIR?=${PHP_DBG_DIST_DIR}

ifneq (${SHARED_ASSET_PATHS},${PHP_DBG_ASSET_DIR})
SHARED_ASSET_PATHS+= ${PHP_DBG_ASSET_DIR}
endif
