// Generated by bin/generate-runtime-types.mjs.
import type { PhpRuntimeArgs } from './public.d.ts';
import type { PhpBase } from './PhpBase.d.cts';

export class PhpNode extends PhpBase {
	constructor(args?: PhpRuntimeArgs);
}
