// Generated by bin/generate-runtime-types.mjs.
import type { PhpRuntimeArgs, PhpRuntimeValue } from './public.d.ts';
import type { PhpBase } from './PhpBase.d.cts';

export class PhpWeb extends PhpBase<[phpCode: string], void> {
	constructor(args?: PhpRuntimeArgs);
	startTransaction(): Promise<void>;
	commitTransaction(readOnly?: boolean): Promise<void>;
	refresh(): Promise<void>;
	_enqueue(callback: (...params: Array<string | number | boolean | object | undefined>) => Promise<PhpRuntimeValue>, params?: Array<string | number | boolean | object | undefined>, readOnly?: boolean): Promise<PhpRuntimeValue>;
}
