// Generated by bin/generate-runtime-types.mjs.
import type { PhpRuntimeArgs } from './public.d.ts';
import type { PhpWebBase } from './PhpWebBase.d.cts';

export class PhpWeb extends PhpWebBase { constructor(args?: PhpRuntimeArgs); }
