// Generated by bin/generate-runtime-types.mjs.
import type { PhpRuntimeArgs, PhpRuntimeValue } from './public.d.ts';
import type { PhpBase } from './PhpBase.d.cts';

export class PhpCliWeb extends PhpBase<[flags?: string[]], void> {
	interactive: boolean;
	script?: string;
	code?: string;
	constructor(args?: PhpRuntimeArgs);
	startTransaction(): Promise<void>;
	commitTransaction(readOnly?: boolean): Promise<void>;
	provideInput(line: string): Promise<void>;
	run(flags?: string[]): Promise<number>;
	refresh(): Promise<void>;
	_enqueue(callback: (...params: Array<string | number | boolean | object | undefined>) => Promise<PhpRuntimeValue>, params?: Array<string | number | boolean | object | undefined>, readOnly?: boolean): Promise<PhpRuntimeValue>;
}
