#!/usr/bin/env make

ifdef PHP_BUILDER_DIR
PHP_CLI_DIST_DIR:=${PHP_BUILDER_DIR}/${PHP_CLI_DIST_DIR}
PHP_CLI_ASSET_DIR:=${PHP_BUILDER_DIR}/${PHP_CLI_ASSET_DIR}
endif
PHP_CLI_DIST_DIR?=${ENV_DIR}/packages/php-cli-wasm
PHP_CLI_ASSET_DIR?=${PHP_CLI_DIST_DIR}

ifneq (${SHARED_ASSET_PATHS},${PHP_CLI_ASSET_DIR})
SHARED_ASSET_PATHS+= ${PHP_CLI_ASSET_DIR}
endif
