#!/usr/bin/env make
WITH_PDO_PGLITE?=1

ifeq (${WITH_PDO_PGLITE},1)
WITH_VRZNO?=1
ifneq (${WITH_VRZNO},1)
$(error WITH_PDO_PGLITE=1 requires WITH_VRZNO=1)
endif

EXTRA_FLAGS+= -D WITH_PDO_PGLITE=1
PDO_PGLITE_SOURCE_STAMP=third_party/pdo-pglite/.php-wasm-source.json
PDO_PGLITE_EXTENSION_STAMP=third_party/php${PHP_VERSION}-src/ext/pdo_pglite/.php-wasm-source.json
PHP_CONFIGURE_DEPS+= ${PDO_PGLITE_EXTENSION_STAMP}
CONFIGURE_FLAGS+= --enable-pdo-pglite
DEPENDENCIES+= ${PDO_PGLITE_EXTENSION_STAMP}
CLI_DEPENDENCIES+= ${PDO_PGLITE_EXTENSION_STAMP}
CGI_DEPENDENCIES+= ${PDO_PGLITE_EXTENSION_STAMP}
DBG_DEPENDENCIES+= ${PDO_PGLITE_EXTENSION_STAMP}
TEST_LIST+=$(wildcard packages/pdo-pglite/test/*.mjs)
endif
