// Generated by bin/generate-runtime-types.mjs.
import type { PhpCgiRuntimeArgs, RuntimeRequest } from './public.d.ts';
import type { PhpCgiBase } from './PhpCgiBase.d.cts';

export type * from './public.d.ts';

export class PhpCgiNode extends PhpCgiBase {
	constructor(args?: PhpCgiRuntimeArgs);
	request(request: RuntimeRequest): Promise<Response | string | undefined>;
}
