// Generated by bin/generate-runtime-types.mjs.
import type { PhpCgiRuntimeArgs, PhpRuntimeValue } from './public.d.ts';
import type { PhpCgiBase } from './PhpCgiBase.d.cts';

export class PhpCgiWebBase extends PhpCgiBase {
	constructor(phpBinLoader: Promise<import('./public.d.ts').PhpCgiModuleFactory>, args?: PhpCgiRuntimeArgs);
	startTransaction(): Promise<void>;
	commitTransaction(readOnly?: boolean): Promise<void>;
	refresh(): Promise<import('./public.d.ts').PhpBinaryRuntime>;
	_enqueue(callback: (...params: Array<string | number | boolean | object | undefined>) => Promise<PhpRuntimeValue>, params?: Array<string | number | boolean | object | undefined>, readOnly?: boolean): Promise<PhpRuntimeValue>;
}
