// Generated by bin/generate-runtime-types.mjs.
import type { PhpCgiRuntimeArgs } from './public.d.ts';
import type { PhpCgiWebBase } from './PhpCgiWebBase.d.cts';

export class PhpCgiWorker extends PhpCgiWebBase {
	constructor(args?: PhpCgiRuntimeArgs);
}
