import { PhpCgiBase } from './PhpCgiBase';
import path from 'node:path';
import url from 'node:url';
import fs from 'node:fs';

const defaultVersion = '8.4';

/**
 * Node.js-hosted PHP CGI wrapper.
 */
export class PhpCgiNode extends PhpCgiBase
{
	/**
	 * Creates a Node.js-hosted PHP CGI runtime.
	 * @param {object} options Runtime configuration.
	 * @param {string} options.docroot Virtual document root served by the runtime.
	 * @param {string} options.prefix URL path prefix routed into the PHP runtime.
	 * @param {(path: string) => string|{scriptName: string, path: string}} options.rewrite URL rewrite callback.
	 * @param {string} options.cookies Persisted cookie data to hydrate the cookie jar with.
	 * @param {{[key: string]: string}} options.types Mapping of file extensions to response MIME types.
	 * @param {(request: Request, response?: Response) => unknown} options.onRequest Hook invoked for each handled request.
	 * @param {(request: Request) => Response|string|undefined} options.notFound Custom 404 handler.
	 * @param {string} options.version PHP version identifier used by the loader.
	 */
	constructor({docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, ...args} = {})
	{
		const locateFile = (name, dir) => {
			if(name.substr(0, 7) === 'file://')
			{
				name = new URL(name).pathname;
			}

			if(dir === '')
			{
				if(typeof __dirname === 'undefined')
				{
					dir = path.dirname(url.fileURLToPath(import.meta.url));
				}
				else
				{
					dir = __dirname;
				}
			}

			const located = path.resolve(path.format({dir, name}));

			if(fs.existsSync(located))
			{
				return located;
			}
		};

		version = version ?? defaultVersion;

		super(
			import(`./php${version}-cgi-node.mjs`)
			, {docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, locateFile, ...args}
		);
	}

	/**
	 * Adapts a Node HTTP request for the shared CGI request handler.
	 * @param {import('node:http').IncomingMessage & {url: string|URL, headers: object}} request Incoming HTTP request.
	 * @returns {Promise<Response|string|undefined>} Response generated by the PHP runtime.
	 */
	async request(request)
	{
		const protocol = request.connection.encrypted ? 'https://' : 'http://';

		request.url = new URL(protocol + request.headers.host + request.url);

		request.headers = new Map(Object.entries(request.headers));

		const response = await super.request(request);

		console.error(`[${new Date().toLocaleString()}] [HTTP ${response.status}] ${String(request.method).padStart(5,' ')} ${request.url}`);

		return response;
	}
}
