import { PhpCgiBase } from './PhpCgiBase';
import path from 'node:path';
import url from 'node:url';
import fs from 'node:fs';

const defaultVersion = '8.4';

/**
 * Node.js-hosted PHP CGI wrapper.
 */
export class PhpCgiNode extends PhpCgiBase
{
	/**
	 * Creates a Node.js-hosted PHP CGI runtime.
	 * @param {object} [options] Runtime configuration.
	 * @param {string} [options.docroot] Virtual document root served by the runtime.
	 * @param {string} [options.prefix] URL path prefix routed into the PHP runtime.
	 * @param {(path: string) => string|{scriptName: string, path: string}} [options.rewrite] URL rewrite callback.
	 * @param {string} [options.entrypoint] Default PHP entrypoint relative to the document root.
	 * @param {string} [options.cookies] Persisted cookie data to hydrate the cookie jar with.
	 * @param {{[key: string]: string}} [options.types] Mapping of file extensions to response MIME types.
	 * @param {PhpRuntimeHook} [options.onRequest] Hook invoked for each handled request.
	 * @param {PhpNotFoundHook} [options.notFound] Custom 404 handler.
	 * @param {PhpLibraryList} [options.sharedLibs] Shared libraries that may be loaded through `php.ini`.
	 * @param {PhpLibraryList} [options.dynamicLibs] Shared libraries that should only be preloaded dynamically.
	 * @param {{[key: string]: PhpActionHandler}} [options.actions] Extra message actions exposed by the wrapper.
	 * @param {PhpPreloadFileList} [options.files] Additional preload files to mount into the runtime.
	 * @param {boolean} [options.autoTransaction] Automatically opens and commits FS transactions around requests.
	 * @param {number} [options.maxRequestAge] Maximum request age in milliseconds before timing out.
	 * @param {number} [options.staticCacheTime] Static asset cache lifetime in milliseconds.
	 * @param {number} [options.dynamicCacheTime] Dynamic response cache lifetime in milliseconds.
	 * @param {PhpVhostList} [options.vHosts] Virtual host routing rules.
	 * @param {{[key: string]: string}} [options.env] Environment variables to set inside the runtime.
	 * @param {string} [options.version] PHP version identifier used by the loader.
	 */
	constructor({docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, ...args} = {})
	{
		const locateFile = (name, dir) => {
			if(name.substr(0, 7) === 'file://')
			{
				name = new URL(name).pathname;
			}

			if(dir === '')
			{
				if(typeof __dirname === 'undefined')
				{
					dir = path.dirname(url.fileURLToPath(import.meta.url));
				}
				else
				{
					dir = __dirname;
				}
			}

			const located = path.resolve(path.format({dir, name}));

			if(fs.existsSync(located))
			{
				return located;
			}
		};

		version = version ?? defaultVersion;

		const constructorArgs = {docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, locateFile, ...args};

		switch(version)
		{
			case '8.5':
				super(import(`./php8.5-cgi-node.mjs`), constructorArgs);
				break;

			case '8.4':
				super(import(`./php8.4-cgi-node.mjs`), constructorArgs);
				break;

			case '8.3':
				super(import(`./php8.3-cgi-node.mjs`), constructorArgs);
				break;

			case '8.2':
				super(import(`./php8.2-cgi-node.mjs`), constructorArgs);
				break;

			case '8.1':
				super(import(`./php8.1-cgi-node.mjs`), constructorArgs);
				break;

			case '8.0':
				super(import(`./php8.0-cgi-node.mjs`), constructorArgs);
				break;

			default:
				throw new Error(`Unsupported PHP runtime: ${version}`);
		}
	}

	/**
	 * Adapts a Node HTTP request for the shared CGI request handler.
	 * @param {RuntimeRequest} request Incoming HTTP request.
	 * @returns {Promise<Response|string|undefined>} Response generated by the PHP runtime.
	 */
	async request(request)
	{
		const protocol = ('connection' in request && request.connection?.encrypted) || ('socket' in request && request.socket?.encrypted)
			? 'https://'
			: 'http://';
		const host = request.headers instanceof Map
			? request.headers.get('host')
			: request.headers instanceof Headers
				? request.headers.get('host')
				: request.headers?.host;
		const requestUrl = new URL(protocol + host + request.url);
		const headers = request.headers instanceof Map
			? request.headers
			: new Map(Object.entries(request.headers instanceof Headers
				? Object.fromEntries(request.headers.entries())
				: request.headers
			));
		const normalizedRequest = {...request, url: requestUrl, headers};

		const response = await super.request(normalizedRequest);

		if(response instanceof Response)
		{
			console.error(`[${new Date().toLocaleString()}] [HTTP ${response.status}] ${String(request.method).padStart(5,' ')} ${requestUrl}`);
		}

		return response;
	}
}
