import { PhpCgiBase } from './PhpCgiBase.mjs';
import path from 'node:path';
import url from 'node:url';
import fs from 'node:fs';

const defaultVersion = '8.4';
const normalizeRuntimeModule = runtime => runtime && typeof runtime === 'object' && 'default' in runtime
	? runtime
	: {default: runtime};

const loadRuntime = specifier => {
	if(typeof require === 'function')
	{
		return Promise.resolve(
			normalizeRuntimeModule(require(specifier.replace(/\.mjs$/, '.js')))
		);
	}

	return import(specifier).then(normalizeRuntimeModule);
};

/** @import { PhpCgiRuntimeArgs } from 'php-cgi-wasm/public' */

/**
 * Node.js-hosted PHP CGI wrapper.
 */
export class PhpCgiNode extends PhpCgiBase
{
	/**
	 * Creates a Node.js-hosted PHP CGI runtime.
	 * @param {PhpCgiRuntimeArgs} [options] Runtime configuration.
	 */
	constructor({docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, ...args} = {})
	{
		const locateFile = (name, dir) => {
			if(name.substr(0, 7) === 'file://')
			{
				name = new URL(name).pathname;
			}

			if(dir === '')
			{
				if(typeof __dirname === 'undefined')
				{
					dir = path.dirname(url.fileURLToPath(import.meta.url));
				}
				else
				{
					dir = __dirname;
				}
			}

			const located = path.resolve(path.format({dir, name}));

			if(fs.existsSync(located))
			{
				return located;
			}
		};

		version = version ?? defaultVersion;

		const constructorArgs = {docroot, prefix, rewrite, cookies, types, onRequest, notFound, version, locateFile, ...args};

		switch(version)
		{
			case '8.5':
				super(loadRuntime('./php8.5-cgi-node.mjs'), constructorArgs);
				break;

			case '8.4':
				super(loadRuntime('./php8.4-cgi-node.mjs'), constructorArgs);
				break;

			case '8.3':
				super(loadRuntime('./php8.3-cgi-node.mjs'), constructorArgs);
				break;

			case '8.2':
				super(loadRuntime('./php8.2-cgi-node.mjs'), constructorArgs);
				break;

			case '8.1':
				super(loadRuntime('./php8.1-cgi-node.mjs'), constructorArgs);
				break;

			case '8.0':
				super(loadRuntime('./php8.0-cgi-node.mjs'), constructorArgs);
				break;

			default:
				throw new Error(`Unsupported PHP runtime: ${version}`);
		}
	}

	/**
	 * Adapts a Node HTTP request for the shared CGI request handler.
	 * @param {RuntimeRequest} request Incoming HTTP request.
	 * @returns {Promise<Response|string|undefined>} Response generated by the PHP runtime.
	 */
	async request(request)
	{
		const protocol = ('connection' in request && request.connection?.encrypted) || ('socket' in request && request.socket?.encrypted)
			? 'https://'
			: 'http://';
		const host = request.headers instanceof Map
			? request.headers.get('host')
			: request.headers instanceof Headers
				? request.headers.get('host')
				: request.headers?.host;
		const requestUrl = new URL(protocol + host + request.url);
		const headers = request.headers instanceof Map
			? request.headers
			: new Map(Object.entries(request.headers instanceof Headers
				? Object.fromEntries(request.headers.entries())
				: request.headers
			));
		const normalizedRequest = {...request, url: requestUrl, headers};

		const response = await super.request(normalizedRequest);

		if(response instanceof Response)
		{
			console.error(`[${new Date().toLocaleString()}] [HTTP ${response.status}] ${String(request.method).padStart(5,' ')} ${requestUrl}`);
		}

		return response;
	}
}
